import type { ProductDetail, Category, Brand } from '@/types/model';
import type { TierLevel } from '@/lib/tier';
import { RUNNING_SHOES_CATEGORY, CHICKEN_CATEGORY } from './mockData';

// 브랜드 도메인 맵 (Google Favicon API 활용)
const BRAND_DOMAINS: Record<string, string> = {
  // 러닝화
  'asics': 'asics.com',
  'nike': 'nike.com',
  'hoka': 'hoka.com',
  'new-balance': 'newbalance.com',
  'saucony': 'saucony.com',
  'adidas': 'adidas.com',
  'mizuno': 'mizuno.com',
  'brooks': 'brooksrunning.com',
  'on-running': 'on.com',
  'puma': 'puma.com',
  'under-armour': 'underarmour.com',
  'reebok': 'reebok.com',
  // 치킨
  'bhc': 'bhc.co.kr',
  'bbq': 'bbq.co.kr',
  'kyochon': 'kyochon.com',
  'goobne': 'goobne.co.kr',
  'nene': 'nenechicken.com',
  'puradak': 'puradak.co.kr',
  'hosik': 'hosigi.com',
  'pericana': 'pelicana.co.kr',
  'chickenmania': 'chickenmania.co.kr',
  'jadam': 'jadamchicken.com',
  'sixtygye': '60chicken.co.kr',
  'ddoraeore': 'ddoraeore.com',
  'mexicana': 'mexicana.co.kr',
  'norangtong': 'norangtongdak.com',
  'cheogajip': 'cheogajip.co.kr',
  'momstouch': 'momstouch.co.kr',
  'jicoba': 'jicoba.co.kr',
  'hollala': 'hollala.co.kr',
  'chickenplus': 'chickenplus.co.kr',
};

// 브랜드 정보 헬퍼
const createBrand = (id: number, name: string, slug: string, tier: TierLevel, score: number, category: string): Brand => ({
  id,
  name,
  slug,
  logo_url: `https://www.google.com/s2/favicons?domain=${BRAND_DOMAINS[slug] || `${slug}.com`}&sz=128`,
  tier,
  tier_score: score,
  category,
});

// 러닝화 브랜드
const ASICS = createBrand(1, '아식스', 'asics', 'S', 95, 'running-shoes');
const NIKE = createBrand(2, '나이키', 'nike', 'S', 94, 'running-shoes');
const HOKA = createBrand(3, '호카', 'hoka', 'S', 92.5, 'running-shoes');
const NEW_BALANCE = createBrand(4, '뉴발란스', 'new-balance', 'A', 88, 'running-shoes');
const SAUCONY = createBrand(5, '써코니', 'saucony', 'A', 87, 'running-shoes');
const ADIDAS = createBrand(7, '아디다스', 'adidas', 'A', 85.5, 'running-shoes');
const MIZUNO = createBrand(8, '미즈노', 'mizuno', 'B', 82, 'running-shoes');
const BROOKS = createBrand(6, '브룩스', 'brooks', 'A', 86.5, 'running-shoes');
const ON_RUNNING = createBrand(9, '온러닝', 'on-running', 'S', 91, 'running-shoes');
const PUMA = createBrand(10, '푸마', 'puma', 'B', 80, 'running-shoes');
const UNDER_ARMOUR = createBrand(11, '언더아머', 'under-armour', 'B', 81, 'running-shoes');
const REEBOK = createBrand(12, '리복', 'reebok', 'B', 78, 'running-shoes');

// 치킨 브랜드
const BHC = createBrand(101, 'BHC', 'bhc', 'S', 94, 'chicken');
const BBQ = createBrand(102, 'BBQ', 'bbq', 'S', 95, 'chicken');
const KYOCHON = createBrand(103, '교촌', 'kyochon', 'S', 93, 'chicken');
const GOOBNE = createBrand(104, '굽네', 'goobne', 'A', 87, 'chicken');
const NENE = createBrand(105, '네네', 'nene', 'A', 86.5, 'chicken');
const PURADAK = createBrand(106, '푸라닭', 'puradak', 'A', 86, 'chicken');
const HOSIK = createBrand(107, '호식이', 'hosik', 'B', 82, 'chicken');
const PERICANA = createBrand(108, '페리카나', 'pericana', 'A', 85, 'chicken');
const CHICKENMANIA = createBrand(109, '치킨매니아', 'chickenmania', 'A', 84, 'chicken');
const JADAM = createBrand(110, '자담치킨', 'jadam', 'A', 85.5, 'chicken');
const SIXTYGYE = createBrand(111, '60계치킨', 'sixtygye', 'A', 86, 'chicken');
const DDORAEORE = createBrand(112, '또래오래', 'ddoraeore', 'B', 83, 'chicken');
const MEXICANA = createBrand(113, '멕시카나', 'mexicana', 'A', 84.5, 'chicken');
const NORANGTONG = createBrand(114, '노랑통닭', 'norangtong', 'B', 81, 'chicken');
const CHEOGAJIP = createBrand(115, '처갓집', 'cheogajip', 'A', 85, 'chicken');
const MOMSTOUCH = createBrand(116, '맘스터치', 'momstouch', 'A', 88, 'chicken');
const JICOBA = createBrand(117, '지코바', 'jicoba', 'B', 80, 'chicken');
const HOLLALA = createBrand(118, '훌랄라', 'hollala', 'B', 79, 'chicken');
const CHICKENPLUS = createBrand(119, '치킨플러스', 'chickenplus', 'B', 80, 'chicken');
const PELICANA = createBrand(120, '페리카나', 'pelicana', 'A', 84, 'chicken');

// 러닝화 Mock 제품 데이터
export const RUNNING_SHOES_PRODUCTS: Record<string, ProductDetail> = {
  'novablast-4': {
    id: 1,
    name: '노바블라스트 4',
    slug: 'novablast-4',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 92.5,
    trend: 'up',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 159000,
    price_max: 189000,
    review_count: 89,
    description: '아식스의 대표적인 데일리 러닝화. FF BLAST PLUS 미드솔로 트램폴린 같은 반발력을 제공합니다.',
    coupang_link: 'https://www.coupang.com/',
    naver_link: 'https://search.shopping.naver.com/',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '258', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '41/33', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF BLAST PLUS', label: '미드솔' },
      { key: 'upper', value: '엔지니어드 메쉬', label: '어퍼' },
    ],
    scores: [
      { key: 'cushion', value: 95, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 90, label: '반응성', weight: 25 },
      { key: 'stability', value: 85, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '사이즈', trap_description: '발볼이 넓은 분은 반 사이즈 업 권장' },
      { id: 2, trap_type: '그립', trap_description: '젖은 노면에서 미끄러울 수 있음' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리 러닝' },
  },
  'alphafly-3': {
    id: 2,
    name: '알파플라이 3',
    slug: 'alphafly-3',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 97,
    trend: 'stable',
    product_type: 'racing',
    usage: 'race',
    price_min: 349000,
    price_max: 399000,
    review_count: 156,
    description: '나이키의 최상위 레이싱화. 마라톤 세계신기록을 달성한 신발로, 풀렝스 카본 플레이트와 ZoomX 폼이 장착되어 있습니다.',
    coupang_link: 'https://www.coupang.com/',
    naver_link: 'https://search.shopping.naver.com/',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '215', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/36', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '4', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'ZoomX + Carbon Plate', label: '미드솔' },
      { key: 'upper', value: 'AtomKnit 3.0', label: '어퍼' },
    ],
    scores: [
      { key: 'cushion', value: 92, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 98, label: '반응성', weight: 25 },
      { key: 'stability', value: 78, label: '안정성', weight: 25 },
      { key: 'durability', value: 72, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '가격', trap_description: '프리미엄 가격대로 레이스 전용 권장' },
      { id: 2, trap_type: '내구성', trap_description: '약 300-400km 수명, 대회용으로 아껴 사용' },
    ],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤/하프' },
  },
  'vaporfly-3': {
    id: 3,
    name: '베이퍼플라이 3',
    slug: 'vaporfly-3',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 96,
    trend: 'stable',
    product_type: 'racing',
    usage: 'race',
    price_min: 289000,
    price_max: 329000,
    review_count: 203,
    description: '나이키의 대표 레이싱화. 알파플라이보다 가볍고 안정적인 느낌으로 다양한 거리에 적합합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '185', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/32', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'ZoomX + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 96, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 75, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '레이스' },
  },
  'clifton-9': {
    id: 4,
    name: '클리프톤 9',
    slug: 'clifton-9',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 93,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 169000,
    price_max: 199000,
    review_count: 312,
    description: '호카의 베스트셀러. 가볍고 푹신한 쿠셔닝으로 입문자부터 베테랑까지 사랑받는 제품입니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '248', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/30', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Compression Molded EVA', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 96, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 88, label: '안정성', weight: 25 },
      { key: 'durability', value: 85, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '사이즈', trap_description: '정사이즈 또는 5mm 업 권장' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리/입문' },
  },
  'gel-kayano-31': {
    id: 5,
    name: '젤 카야노 31',
    slug: 'gel-kayano-31',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 94,
    trend: 'up',
    product_type: 'stability',
    usage: 'daily',
    price_min: 189000,
    price_max: 229000,
    review_count: 178,
    description: '아식스의 대표 안정화. 30년 이상의 역사를 가진 제품으로 오버프로네이션 러너에게 최적화되어 있습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '295', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/30', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF BLAST PLUS + 4D GUIDANCE SYSTEM', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 94, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 85, label: '반응성', weight: 25 },
      { key: 'stability', value: 98, label: '안정성', weight: 25 },
      { key: 'durability', value: 92, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '안정화', usage: '장거리' },
  },
  'gel-nimbus-26': {
    id: 6,
    name: '젤 님버스 26',
    slug: 'gel-nimbus-26',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 93,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 179000,
    price_max: 219000,
    review_count: 245,
    description: '아식스의 프리미엄 쿠션화. 젤 쿠셔닝과 FF BLAST PLUS가 결합되어 최상의 편안함을 제공합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '280', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '41/31', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF BLAST PLUS ECO + PureGEL', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 97, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 85, label: '안정성', weight: 25 },
      { key: 'durability', value: 90, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '장거리/입문' },
  },
  'mach-6': {
    id: 7,
    name: '마하 6',
    slug: 'mach-6',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 91,
    trend: 'up',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 159000,
    price_max: 189000,
    review_count: 167,
    description: '호카의 경량 데일리 트레이너. 부드러운 쿠셔닝과 가벼운 무게로 템포런에도 적합합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '232', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '37/32', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'PEBA Foam', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 90, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 92, label: '반응성', weight: 25 },
      { key: 'stability', value: 84, label: '안정성', weight: 25 },
      { key: 'durability', value: 82, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리/템포' },
  },
  'pegasus-41': {
    id: 8,
    name: '페가수스 41',
    slug: 'pegasus-41',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 149000,
    price_max: 169000,
    review_count: 425,
    description: '나이키의 대표 데일리 러닝화. 40년 이상의 역사를 가진 베스트셀러로 다양한 러너에게 적합합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '272', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '33/23', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'React + Air Zoom', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 85, label: '반응성', weight: 25 },
      { key: 'stability', value: 88, label: '안정성', weight: 25 },
      { key: 'durability', value: 90, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'bondi-8': {
    id: 9,
    name: '본디 8',
    slug: 'bondi-8',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 92,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 189000,
    price_max: 219000,
    review_count: 289,
    description: '호카의 맥시멀 쿠션화. 푹신한 착화감으로 장시간 러닝에도 편안합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '307', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '37/33', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '4', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Compression Molded EVA', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 98, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 78, label: '반응성', weight: 25 },
      { key: 'stability', value: 88, label: '안정성', weight: 25 },
      { key: 'durability', value: 86, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '무게', trap_description: '상대적으로 무거운 편으로 스피드 러닝에는 부적합' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '장거리/입문' },
  },
  '1080-v13': {
    id: 10,
    name: '1080 v13',
    slug: '1080-v13',
    brand: NEW_BALANCE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 89,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 179000,
    price_max: 209000,
    review_count: 198,
    description: '뉴발란스의 프리미엄 쿠션화. Fresh Foam X 미드솔로 부드러운 착화감을 제공합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '283', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/29', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '6', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Fresh Foam X', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 92, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 84, label: '반응성', weight: 25 },
      { key: 'stability', value: 86, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  // 추가 러닝화 제품들
  'endorphin-speed-4': {
    id: 11,
    name: '엔돌핀 스피드 4',
    slug: 'endorphin-speed-4',
    brand: SAUCONY,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 94,
    trend: 'up',
    product_type: 'racing',
    usage: 'tempo',
    price_min: 199000,
    price_max: 229000,
    review_count: 245,
    description: '써코니의 인기 템포 러닝화. 나일론 플레이트와 PWRRUN PB 폼이 조화를 이룹니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '215', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/32', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'PWRRUN PB + Nylon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 95, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 80, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '템포/레이스' },
  },
  'invincible-3': {
    id: 12,
    name: '인빈서블 3',
    slug: 'invincible-3',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 92,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 189000,
    price_max: 219000,
    review_count: 312,
    description: '나이키의 맥시멀 쿠션화. ZoomX 폼이 가득 차 있어 구름 위를 걷는 느낌을 줍니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '299', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '37/37', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '0', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'ZoomX', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 98, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 78, label: '안정성', weight: 25 },
      { key: 'durability', value: 85, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '안정성', trap_description: '폭신한 쿠션으로 인해 옆으로 흔들릴 수 있음' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '리커버리/장거리' },
  },
  'ghost-16': {
    id: 13,
    name: '고스트 16',
    slug: 'ghost-16',
    brand: BROOKS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 169000,
    price_max: 199000,
    review_count: 278,
    description: '브룩스의 베스트셀러. DNA LOFT v2로 부드러우면서도 안정적인 주행감을 제공합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '281', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/23', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '12', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'DNA LOFT v2', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 90, label: '안정성', weight: 25 },
      { key: 'durability', value: 92, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'glycerin-21': {
    id: 14,
    name: '글리세린 21',
    slug: 'glycerin-21',
    brand: BROOKS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 89,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 189000,
    price_max: 219000,
    review_count: 198,
    description: '브룩스의 프리미엄 쿠션화. DNA LOFT v3로 최상의 편안함을 제공합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '290', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '38/28', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'DNA LOFT v3', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 95, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 80, label: '반응성', weight: 25 },
      { key: 'stability', value: 88, label: '안정성', weight: 25 },
      { key: 'durability', value: 90, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '장거리' },
  },
  'cloudmonster': {
    id: 15,
    name: '클라우드몬스터',
    slug: 'cloudmonster',
    brand: ON_RUNNING,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 91,
    trend: 'up',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 199000,
    price_max: 229000,
    review_count: 234,
    description: '온러닝의 인기 쿠션화. CloudTec Phase로 부드러운 착지와 강한 추진력을 제공합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '275', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/25', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'CloudTec Phase + Helion', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 92, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 88, label: '반응성', weight: 25 },
      { key: 'stability', value: 85, label: '안정성', weight: 25 },
      { key: 'durability', value: 84, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '그립', trap_description: '젖은 노면에서 미끄러울 수 있음' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'cloudsurfer': {
    id: 16,
    name: '클라우드서퍼',
    slug: 'cloudsurfer',
    brand: ON_RUNNING,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 189000,
    price_max: 219000,
    review_count: 178,
    description: '온러닝의 데일리 러닝화. CloudTec과 Speedboard가 결합되어 있습니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '280', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '36/26', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'CloudTec + Helion', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 86, label: '반응성', weight: 25 },
      { key: 'stability', value: 86, label: '안정성', weight: 25 },
      { key: 'durability', value: 85, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'kinvara-15': {
    id: 17,
    name: '킨바라 15',
    slug: 'kinvara-15',
    brand: SAUCONY,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 149000,
    price_max: 179000,
    review_count: 198,
    description: '써코니의 경량 데일리화. 가볍고 반응성이 좋아 템포런에도 적합합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '215', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '28/24', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '4', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'PWRRUN+', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 82, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 90, label: '반응성', weight: 25 },
      { key: 'stability', value: 84, label: '안정성', weight: 25 },
      { key: 'durability', value: 82, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리/템포' },
  },
  'triumph-22': {
    id: 18,
    name: '트라이엄프 22',
    slug: 'triumph-22',
    brand: SAUCONY,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 179000,
    price_max: 209000,
    review_count: 167,
    description: '써코니의 프리미엄 쿠션화. PWRRUN PB로 푹신하면서도 반응성이 좋습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '272', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '36/28', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'PWRRUN PB', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 94, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 86, label: '반응성', weight: 25 },
      { key: 'stability', value: 85, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '장거리' },
  },
  'ultraboost-light': {
    id: 19,
    name: '울트라부스트 라이트',
    slug: 'ultraboost-light',
    brand: ADIDAS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 189000,
    price_max: 229000,
    review_count: 234,
    description: '아디다스의 대표 러닝화. 경량 BOOST 폼으로 편안한 착화감을 제공합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '285', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '31/21', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Light BOOST', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 90, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 84, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'adizero-adios-pro-3': {
    id: 20,
    name: '아디제로 아디오스 프로 3',
    slug: 'adizero-adios-pro-3',
    brand: ADIDAS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 95,
    trend: 'stable',
    product_type: 'racing',
    usage: 'race',
    price_min: 269000,
    price_max: 299000,
    review_count: 145,
    description: '아디다스의 최상위 레이싱화. 5핑거 카본과 LIGHTSTRIKE PRO가 장착되어 있습니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '215', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '39/39', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '0', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'LIGHTSTRIKE PRO + Carbon Rods', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 96, label: '반응성', weight: 25 },
      { key: 'stability', value: 80, label: '안정성', weight: 25 },
      { key: 'durability', value: 72, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '내구성', trap_description: '레이스 전용으로 약 200-300km 수명' },
    ],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤' },
  },
  'boston-12': {
    id: 21,
    name: '보스턴 12',
    slug: 'boston-12',
    brand: ADIDAS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'up',
    product_type: 'cushion',
    usage: 'tempo',
    price_min: 169000,
    price_max: 199000,
    review_count: 189,
    description: '아디다스의 템포 러닝화. 가벼우면서도 반응성이 좋아 훈련에 적합합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '245', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '39/28', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '11', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'LIGHTSTRIKE PRO + Glass Fiber Rods', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 90, label: '반응성', weight: 25 },
      { key: 'stability', value: 84, label: '안정성', weight: 25 },
      { key: 'durability', value: 82, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '템포' },
  },
  'fuelcell-rebel-v4': {
    id: 22,
    name: '퓨얼셀 레벨 v4',
    slug: 'fuelcell-rebel-v4',
    brand: NEW_BALANCE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 89,
    trend: 'up',
    product_type: 'cushion',
    usage: 'tempo',
    price_min: 159000,
    price_max: 189000,
    review_count: 198,
    description: '뉴발란스의 인기 템포화. 가볍고 반응성이 좋아 다양한 용도로 활용 가능합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '225', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '34/28', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '6', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FuelCell', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 85, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 92, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 80, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '템포/데일리' },
  },
  'supercomp-elite-v4': {
    id: 23,
    name: '슈퍼컴프 엘리트 v4',
    slug: 'supercomp-elite-v4',
    brand: NEW_BALANCE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 94,
    trend: 'stable',
    product_type: 'racing',
    usage: 'race',
    price_min: 279000,
    price_max: 309000,
    review_count: 134,
    description: '뉴발란스의 최상위 레이싱화. 풀렝스 카본과 에너지 아크가 장착되어 있습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '208', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '42/34', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FuelCell + Carbon Plate + Energy Arc', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 90, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 96, label: '반응성', weight: 25 },
      { key: 'stability', value: 78, label: '안정성', weight: 25 },
      { key: 'durability', value: 70, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '내구성', trap_description: '레이스 전용으로 아껴 사용 권장' },
    ],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤' },
  },
  'rincon-4': {
    id: 24,
    name: '린콘 4',
    slug: 'rincon-4',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 139000,
    price_max: 169000,
    review_count: 245,
    description: '호카의 경량 러닝화. 가볍고 반응성이 좋아 가성비 최고의 입문용 신발입니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '218', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '32/27', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Compression Molded EVA', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 84, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 88, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 78, label: '내구성', weight: 25 },
    ],
    traps: [
      { id: 1, trap_type: '내구성', trap_description: '가벼운 대신 내구성이 다소 낮음' },
    ],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리/입문' },
  },
  'arahi-7': {
    id: 25,
    name: '아라히 7',
    slug: 'arahi-7',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'stability',
    usage: 'daily',
    price_min: 169000,
    price_max: 199000,
    review_count: 178,
    description: '호카의 경량 안정화. J-Frame 기술로 오버프로네이션을 방지합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '262', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '33/28', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Compression Molded EVA + J-Frame', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 94, label: '안정성', weight: 25 },
      { key: 'durability', value: 86, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '안정화', usage: '데일리' },
  },
  'rocket-x-2': {
    id: 26,
    name: '로켓 X 2',
    slug: 'rocket-x-2',
    brand: HOKA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 93,
    trend: 'stable',
    product_type: 'racing',
    usage: 'race',
    price_min: 269000,
    price_max: 299000,
    review_count: 156,
    description: '호카의 레이싱화. 카본 플레이트와 PEBA 폼이 결합되어 있습니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '210', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '38/33', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'PEBA + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 95, label: '반응성', weight: 25 },
      { key: 'stability', value: 80, label: '안정성', weight: 25 },
      { key: 'durability', value: 72, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤' },
  },
  'metaspeed-sky-paris': {
    id: 27,
    name: '메타스피드 스카이 파리',
    slug: 'metaspeed-sky-paris',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 96,
    trend: 'up',
    product_type: 'racing',
    usage: 'race',
    price_min: 289000,
    price_max: 319000,
    review_count: 189,
    description: '아식스의 최상위 레이싱화. FF TURBO PLUS와 풀렝스 카본이 장착되어 있습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '195', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/35', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '5', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF TURBO PLUS + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 88, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 97, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 70, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤' },
  },
  'magic-speed-4': {
    id: 28,
    name: '매직 스피드 4',
    slug: 'magic-speed-4',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 89,
    trend: 'up',
    product_type: 'racing',
    usage: 'tempo',
    price_min: 169000,
    price_max: 199000,
    review_count: 234,
    description: '아식스의 템포/레이싱화. 카본 플레이트가 장착된 가성비 좋은 선택입니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '230', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '41/33', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF BLAST+ + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 92, label: '반응성', weight: 25 },
      { key: 'stability', value: 84, label: '안정성', weight: 25 },
      { key: 'durability', value: 78, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '템포/레이스' },
  },
  'superblast-2': {
    id: 29,
    name: '슈퍼블라스트 2',
    slug: 'superblast-2',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 93,
    trend: 'up',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 199000,
    price_max: 229000,
    review_count: 145,
    description: '아식스의 맥시멀 쿠션화. FF TURBO PLUS로 뛰어난 에너지 리턴을 제공합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '275', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '46/38', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF TURBO PLUS', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 96, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 90, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 84, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리/장거리' },
  },
  'gt-2000-13': {
    id: 30,
    name: 'GT-2000 13',
    slug: 'gt-2000-13',
    brand: ASICS,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'stability',
    usage: 'daily',
    price_min: 149000,
    price_max: 179000,
    review_count: 198,
    description: '아식스의 대표 안정화. 3D GUIDANCE SYSTEM으로 안정적인 주행을 지원합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '275', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '37/27', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'FF BLAST+ + 3D GUIDANCE SYSTEM', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 84, label: '반응성', weight: 25 },
      { key: 'stability', value: 94, label: '안정성', weight: 25 },
      { key: 'durability', value: 90, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '안정화', usage: '데일리' },
  },
  'wave-rider-28': {
    id: 31,
    name: '웨이브 라이더 28',
    slug: 'wave-rider-28',
    brand: MIZUNO,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 85,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 159000,
    price_max: 189000,
    review_count: 178,
    description: '미즈노의 대표 쿠션화. 웨이브 플레이트로 안정성과 쿠셔닝을 동시에 제공합니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '285', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/23', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '12', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'ENERZY + Wave Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 90, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '데일리' },
  },
  'wave-rebellion-pro-2': {
    id: 32,
    name: '웨이브 레벨리온 프로 2',
    slug: 'wave-rebellion-pro-2',
    brand: MIZUNO,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'up',
    product_type: 'racing',
    usage: 'race',
    price_min: 249000,
    price_max: 279000,
    review_count: 98,
    description: '미즈노의 레이싱화. 카본 플레이트와 G3 ENERZY ELITE가 장착되어 있습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '210', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '45/37', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'G3 ENERZY ELITE + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 94, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 74, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '레이싱화', usage: '마라톤' },
  },
  'zoom-fly-5': {
    id: 33,
    name: '줌 플라이 5',
    slug: 'zoom-fly-5',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'tempo',
    price_min: 169000,
    price_max: 199000,
    review_count: 234,
    description: '나이키의 템포 러닝화. 카본 플레이트와 ZoomX 폼이 결합되어 있습니다.',
    release_year: 2022,
    specs: [
      { key: 'weight', value: '250', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '40/32', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'ZoomX + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 86, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 90, label: '반응성', weight: 25 },
      { key: 'stability', value: 82, label: '안정성', weight: 25 },
      { key: 'durability', value: 78, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '템포' },
  },
  'structure-25': {
    id: 34,
    name: '스트럭처 25',
    slug: 'structure-25',
    brand: NIKE,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'stability',
    usage: 'daily',
    price_min: 149000,
    price_max: 179000,
    review_count: 167,
    description: '나이키의 안정화. 오버프로네이션 러너를 위한 지지력을 제공합니다.',
    release_year: 2023,
    specs: [
      { key: 'weight', value: '285', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '35/25', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '10', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'Nike React + Crash Rail', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 84, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 82, label: '반응성', weight: 25 },
      { key: 'stability', value: 94, label: '안정성', weight: 25 },
      { key: 'durability', value: 88, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '안정화', usage: '데일리' },
  },
  'deviate-nitro-3': {
    id: 35,
    name: '디비에이트 니트로 3',
    slug: 'deviate-nitro-3',
    brand: PUMA,
    category_slug: 'running-shoes',
    category: RUNNING_SHOES_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 82,
    trend: 'stable',
    product_type: 'cushion',
    usage: 'daily',
    price_min: 159000,
    price_max: 189000,
    review_count: 134,
    description: '푸마의 템포 러닝화. NITRO 폼과 카본 플레이트가 장착되어 있습니다.',
    release_year: 2024,
    specs: [
      { key: 'weight', value: '265', label: '무게', unit: 'g' },
      { key: 'stack_height', value: '37/29', label: '스택 높이', unit: 'mm' },
      { key: 'drop', value: '8', label: '드롭', unit: 'mm' },
      { key: 'midsole', value: 'NITRO Foam + Carbon Plate', label: '미드솔' },
    ],
    scores: [
      { key: 'cushion', value: 82, label: '쿠셔닝', weight: 25 },
      { key: 'responsiveness', value: 86, label: '반응성', weight: 25 },
      { key: 'stability', value: 80, label: '안정성', weight: 25 },
      { key: 'durability', value: 78, label: '내구성', weight: 25 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '쿠션화', usage: '템포' },
  },
};

// 치킨 Mock 제품 데이터
export const CHICKEN_PRODUCTS: Record<string, ProductDetail> = {
  'bhc-puringkle': {
    id: 101,
    name: '뿌링클',
    slug: 'bhc-puringkle',
    brand: BHC,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 97,
    trend: 'stable',
    product_type: 'powder',
    usage: 'party',
    price_min: 19000,
    price_max: 22000,
    review_count: 342,
    description: 'BHC의 시그니처 메뉴. 특제 치즈 시즈닝이 뿌려진 바삭한 치킨으로, 10년 연속 인기 1위 메뉴입니다.',
    coupang_link: '',
    naver_link: '',
    release_year: 2014,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '순한맛', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 96, label: '맛', weight: 35 },
      { key: 'price', value: 85, label: '가성비', weight: 25 },
      { key: 'crispy', value: 94, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 98, label: '인기도', weight: 20 },
    ],
    traps: [
      { id: 1, trap_type: '양', trap_description: '양이 조금 아쉬울 수 있으니 콤보 추천' },
      { id: 2, trap_type: '시간', trap_description: '치즈가 식으면 눅눅해질 수 있음' },
    ],
    alternatives: [],
    filter_labels: { product_type: '가루/시즈닝', usage: '치맥/파티' },
  },
  'bbq-golden-olive': {
    id: 102,
    name: '황금올리브치킨',
    slug: 'bbq-golden-olive',
    brand: BBQ,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 96,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 20000,
    price_max: 23000,
    review_count: 278,
    description: 'BBQ의 대표 메뉴. 스페인산 올리브유로 튀겨 담백하고 바삭한 맛이 특징입니다.',
    release_year: 2005,
    specs: [
      { key: 'type', value: '튀김 (올리브유)', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 95, label: '맛', weight: 35 },
      { key: 'price', value: 82, label: '가성비', weight: 25 },
      { key: 'crispy', value: 96, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 94, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '치맥/식사' },
  },
  'kyochon-original': {
    id: 103,
    name: '교촌 오리지날',
    slug: 'kyochon-original',
    brand: KYOCHON,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 95,
    trend: 'stable',
    product_type: 'soy',
    usage: 'meal',
    price_min: 19000,
    price_max: 22000,
    review_count: 356,
    description: '교촌치킨의 시그니처 메뉴. 달짭한 간장 소스가 배어든 치킨으로, 밥반찬으로도 좋습니다.',
    release_year: 1991,
    specs: [
      { key: 'type', value: '튀김 + 간장 소스', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 94, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 95, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '간장/허니', usage: '식사대용' },
  },
  'goobne-gochu': {
    id: 104,
    name: '고추바사삭',
    slug: 'goobne-gochu',
    brand: GOOBNE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 90,
    trend: 'up',
    product_type: 'roasted',
    usage: 'party',
    price_min: 19000,
    price_max: 22000,
    review_count: 189,
    description: '굽네치킨의 대표 메뉴. 오븐에 구워 기름기가 적고, 매콤한 시즈닝이 특징입니다.',
    release_year: 2015,
    specs: [
      { key: 'type', value: '오븐 구이', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 89, label: '맛', weight: 35 },
      { key: 'price', value: 85, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 90, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '구이', usage: '치맥/파티' },
  },
  'bhc-matchoking': {
    id: 105,
    name: '맛초킹',
    slug: 'bhc-matchoking',
    brand: BHC,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'soy',
    usage: 'meal',
    price_min: 18000,
    price_max: 21000,
    review_count: 167,
    description: 'BHC의 인기 간장 치킨. 달콤한 간장 소스에 고추가 어우러져 매콤달콤한 맛입니다.',
    release_year: 2018,
    specs: [
      { key: 'type', value: '튀김 + 간장 소스', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '약간 매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 86, label: '가성비', weight: 25 },
      { key: 'crispy', value: 84, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 87, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '간장/허니', usage: '식사대용' },
  },
  'nene-snowing': {
    id: 106,
    name: '스노윙치즈',
    slug: 'nene-snowing',
    brand: NENE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'powder',
    usage: 'party',
    price_min: 18000,
    price_max: 21000,
    review_count: 145,
    description: '네네치킨의 인기 메뉴. 눈처럼 하얀 치즈 파우더가 뿌려진 치킨입니다.',
    release_year: 2017,
    specs: [
      { key: 'type', value: '튀김 + 치즈 시즈닝', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 87, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 88, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '가루/시즈닝', usage: '파티' },
  },
  'bbq-jamaica': {
    id: 107,
    name: '자메이카 통다리',
    slug: 'bbq-jamaica',
    brand: BBQ,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'roasted',
    usage: 'meal',
    price_min: 18000,
    price_max: 21000,
    review_count: 134,
    description: 'BBQ의 저크 시즈닝 치킨. 이국적인 향신료 맛이 특징인 통다리 치킨입니다.',
    release_year: 2016,
    specs: [
      { key: 'type', value: '오븐 구이', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '통다리 4개', label: '양' },
      { key: 'spicy', value: '약간 매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 82, label: '가성비', weight: 25 },
      { key: 'crispy', value: 84, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 85, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '구이', usage: '식사대용' },
  },
  'kyochon-red': {
    id: 108,
    name: '레드콤보',
    slug: 'kyochon-red',
    brand: KYOCHON,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 19000,
    price_max: 22000,
    review_count: 178,
    description: '교촌치킨의 양념 메뉴. 달콤하면서도 매콤한 양념 소스가 특징입니다.',
    release_year: 2005,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 83, label: '가성비', weight: 25 },
      { key: 'crispy', value: 82, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 89, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'pericana-yangnyum': {
    id: 109,
    name: '페리카나 양념',
    slug: 'pericana-yangnyum',
    brand: PERICANA,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 85,
    trend: 'stable',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 17000,
    price_max: 20000,
    review_count: 156,
    description: '페리카나의 클래식 양념 치킨. 진한 양념 맛이 특징인 오랜 역사의 메뉴입니다.',
    release_year: 1982,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '17,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 86, label: '맛', weight: 35 },
      { key: 'price', value: 88, label: '가성비', weight: 25 },
      { key: 'crispy', value: 80, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 82, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'puradak-black-allio': {
    id: 110,
    name: '블랙알리오',
    slug: 'puradak-black-allio',
    brand: PURADAK,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'up',
    product_type: 'roasted',
    usage: 'meal',
    price_min: 20000,
    price_max: 23000,
    review_count: 134,
    description: '푸라닭의 프리미엄 메뉴. 마늘 풍미가 가득한 치킨으로 식사 대용으로 좋습니다.',
    release_year: 2019,
    specs: [
      { key: 'type', value: '오븐 구이 + 마늘 소스', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 90, label: '맛', weight: 35 },
      { key: 'price', value: 78, label: '가성비', weight: 25 },
      { key: 'crispy', value: 85, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 84, label: '인기도', weight: 20 },
    ],
    traps: [
      { id: 1, trap_type: '가격', trap_description: '프리미엄 가격대' },
    ],
    alternatives: [],
    filter_labels: { product_type: '구이', usage: '식사대용' },
  },
  'hosik-original': {
    id: 111,
    name: '호식이 후라이드',
    slug: 'hosik-original',
    brand: HOSIK,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 82,
    trend: 'stable',
    product_type: 'fried',
    usage: 'meal',
    price_min: 15000,
    price_max: 18000,
    review_count: 234,
    description: '호식이두마리치킨의 대표 메뉴. 가성비 좋은 후라이드 치킨입니다.',
    release_year: 1999,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '15,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 80, label: '맛', weight: 35 },
      { key: 'price', value: 95, label: '가성비', weight: 25 },
      { key: 'crispy', value: 78, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 75, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '가성비' },
  },
  // 추가 치킨 제품들
  'chickenmania-real-crispy': {
    id: 112,
    name: '리얼후라이드',
    slug: 'chickenmania-real-crispy',
    brand: CHICKENMANIA,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 84,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 17000,
    price_max: 20000,
    review_count: 145,
    description: '치킨매니아의 인기 후라이드. 얇고 바삭한 튀김옷이 특징입니다.',
    release_year: 2010,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '17,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 84, label: '맛', weight: 35 },
      { key: 'price', value: 86, label: '가성비', weight: 25 },
      { key: 'crispy', value: 90, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 82, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '치맥' },
  },
  'jadam-fried': {
    id: 113,
    name: '자담 후라이드',
    slug: 'jadam-fried',
    brand: JADAM,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 85.5,
    trend: 'up',
    product_type: 'fried',
    usage: 'meal',
    price_min: 18000,
    price_max: 21000,
    review_count: 178,
    description: '자담치킨의 대표 메뉴. 국내산 닭을 사용한 프리미엄 후라이드입니다.',
    release_year: 2015,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 82, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 85, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '식사대용' },
  },
  '60gye-original': {
    id: 114,
    name: '60계 오리지널',
    slug: '60gye-original',
    brand: SIXTYGYE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 17000,
    price_max: 20000,
    review_count: 189,
    description: '60계치킨의 시그니처 메뉴. 60년 레시피를 계승한 전통 치킨입니다.',
    release_year: 2012,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '17,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 87, label: '맛', weight: 35 },
      { key: 'price', value: 85, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 84, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '치맥' },
  },
  'ddoraeore-fried': {
    id: 115,
    name: '또래 후라이드',
    slug: 'ddoraeore-fried',
    brand: DDORAEORE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 83,
    trend: 'stable',
    product_type: 'fried',
    usage: 'meal',
    price_min: 16000,
    price_max: 19000,
    review_count: 167,
    description: '또래오래의 기본 메뉴. 합리적인 가격의 후라이드 치킨입니다.',
    release_year: 2006,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '16,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 82, label: '맛', weight: 35 },
      { key: 'price', value: 88, label: '가성비', weight: 25 },
      { key: 'crispy', value: 80, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 78, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '가성비' },
  },
  'mexicana-fried': {
    id: 116,
    name: '멕시카나 후라이드',
    slug: 'mexicana-fried',
    brand: MEXICANA,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 84.5,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 17000,
    price_max: 20000,
    review_count: 145,
    description: '멕시카나의 대표 메뉴. 40년 전통의 치킨 프랜차이즈입니다.',
    release_year: 1985,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '17,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 85, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 82, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '치맥' },
  },
  'norangtong-tongdak': {
    id: 117,
    name: '노랑통닭 후라이드',
    slug: 'norangtong-tongdak',
    brand: NORANGTONG,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 81,
    trend: 'stable',
    product_type: 'fried',
    usage: 'meal',
    price_min: 14000,
    price_max: 17000,
    review_count: 198,
    description: '노랑통닭의 대표 메뉴. 저렴한 가격의 가성비 치킨입니다.',
    release_year: 2000,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '14,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 78, label: '맛', weight: 35 },
      { key: 'price', value: 95, label: '가성비', weight: 25 },
      { key: 'crispy', value: 76, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 75, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '가성비' },
  },
  'cheogajip-yangnyum': {
    id: 118,
    name: '처갓집 양념치킨',
    slug: 'cheogajip-yangnyum',
    brand: CHEOGAJIP,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 85,
    trend: 'stable',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 18000,
    price_max: 21000,
    review_count: 234,
    description: '처갓집양념치킨의 시그니처 메뉴. 달콤하고 매콤한 양념이 특징입니다.',
    release_year: 1999,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 86, label: '맛', weight: 35 },
      { key: 'price', value: 83, label: '가성비', weight: 25 },
      { key: 'crispy', value: 82, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 86, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'momstouch-fried': {
    id: 119,
    name: '맘스후라이드',
    slug: 'momstouch-fried',
    brand: MOMSTOUCH,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 91,
    trend: 'up',
    product_type: 'fried',
    usage: 'meal',
    price_min: 17000,
    price_max: 20000,
    review_count: 289,
    description: '맘스터치의 치킨 메뉴. 수제 방식으로 조리하는 프리미엄 후라이드입니다.',
    release_year: 2018,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '17,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 92, label: '맛', weight: 35 },
      { key: 'price', value: 85, label: '가성비', weight: 25 },
      { key: 'crispy', value: 90, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 92, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '식사대용' },
  },
  'momstouch-yangnyum': {
    id: 120,
    name: '맘스양념',
    slug: 'momstouch-yangnyum',
    brand: MOMSTOUCH,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 90,
    trend: 'up',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 18000,
    price_max: 21000,
    review_count: 256,
    description: '맘스터치의 양념 치킨. 매콤달콤한 양념이 특징입니다.',
    release_year: 2018,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 91, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 90, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'bhc-cheese-ball': {
    id: 121,
    name: '뿌링치즈볼',
    slug: 'bhc-cheese-ball',
    brand: BHC,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 89,
    trend: 'stable',
    product_type: 'powder',
    usage: 'party',
    price_min: 20000,
    price_max: 23000,
    review_count: 198,
    description: 'BHC의 인기 사이드. 뿌링클에 치즈볼을 추가한 세트 메뉴입니다.',
    release_year: 2017,
    specs: [
      { key: 'type', value: '튀김 + 치즈 시즈닝', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 + 치즈볼', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 90, label: '맛', weight: 35 },
      { key: 'price', value: 78, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 92, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '가루/시즈닝', usage: '파티' },
  },
  'bbq-secret-yangnyum': {
    id: 122,
    name: '시크릿양념',
    slug: 'bbq-secret-yangnyum',
    brand: BBQ,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 20000,
    price_max: 23000,
    review_count: 178,
    description: 'BBQ의 양념 치킨. 특제 소스로 맛을 낸 프리미엄 양념입니다.',
    release_year: 2010,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 89, label: '맛', weight: 35 },
      { key: 'price', value: 80, label: '가성비', weight: 25 },
      { key: 'crispy', value: 84, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 87, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'kyochon-honey-combo': {
    id: 123,
    name: '허니콤보',
    slug: 'kyochon-honey-combo',
    brand: KYOCHON,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'S',
    tier_score: 94,
    trend: 'stable',
    product_type: 'soy',
    usage: 'meal',
    price_min: 20000,
    price_max: 23000,
    review_count: 312,
    description: '교촌의 인기 메뉴. 달콤한 꿀과 간장이 어우러진 치킨입니다.',
    release_year: 2008,
    specs: [
      { key: 'type', value: '튀김 + 허니 간장 소스', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 95, label: '맛', weight: 35 },
      { key: 'price', value: 82, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 96, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '간장/허니', usage: '식사대용' },
  },
  'goobne-volcano': {
    id: 124,
    name: '볼케이노',
    slug: 'goobne-volcano',
    brand: GOOBNE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 88,
    trend: 'stable',
    product_type: 'roasted',
    usage: 'party',
    price_min: 19000,
    price_max: 22000,
    review_count: 178,
    description: '굽네의 매운맛 메뉴. 화끈한 매운맛이 특징인 오븐 구이 치킨입니다.',
    release_year: 2016,
    specs: [
      { key: 'type', value: '오븐 구이', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매우 매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 87, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 88, label: '인기도', weight: 20 },
    ],
    traps: [
      { id: 1, trap_type: '맵기', trap_description: '매운맛에 민감한 분은 주의' },
    ],
    alternatives: [],
    filter_labels: { product_type: '구이', usage: '파티' },
  },
  'nene-banban': {
    id: 125,
    name: '반반치킨',
    slug: 'nene-banban',
    brand: NENE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 18000,
    price_max: 21000,
    review_count: 189,
    description: '네네치킨의 인기 메뉴. 두 가지 맛을 한 번에 즐길 수 있습니다.',
    release_year: 2012,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (반반)', label: '양' },
      { key: 'spicy', value: '선택', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 85, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 86, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 87, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '파티' },
  },
  'puradak-garlic': {
    id: 126,
    name: '고추마요치킨',
    slug: 'puradak-garlic',
    brand: PURADAK,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'up',
    product_type: 'yangnyum',
    usage: 'meal',
    price_min: 20000,
    price_max: 23000,
    review_count: 145,
    description: '푸라닭의 인기 메뉴. 고추와 마요네즈가 어우러진 특별한 맛입니다.',
    release_year: 2018,
    specs: [
      { key: 'type', value: '튀김 + 소스', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '약간 매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 78, label: '가성비', weight: 25 },
      { key: 'crispy', value: 84, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 85, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '식사대용' },
  },
  'jicoba-fried': {
    id: 127,
    name: '지코바 후라이드',
    slug: 'jicoba-fried',
    brand: JICOBA,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 80,
    trend: 'stable',
    product_type: 'fried',
    usage: 'meal',
    price_min: 15000,
    price_max: 18000,
    review_count: 134,
    description: '지코바의 기본 메뉴. 가성비 좋은 후라이드 치킨입니다.',
    release_year: 2008,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '15,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 78, label: '맛', weight: 35 },
      { key: 'price', value: 92, label: '가성비', weight: 25 },
      { key: 'crispy', value: 76, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 72, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '가성비' },
  },
  'hollala-fried': {
    id: 128,
    name: '훌랄라 후라이드',
    slug: 'hollala-fried',
    brand: HOLLALA,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 79,
    trend: 'stable',
    product_type: 'fried',
    usage: 'meal',
    price_min: 14000,
    price_max: 17000,
    review_count: 112,
    description: '훌랄라의 기본 메뉴. 저렴한 가격의 후라이드 치킨입니다.',
    release_year: 2005,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '14,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 76, label: '맛', weight: 35 },
      { key: 'price', value: 94, label: '가성비', weight: 25 },
      { key: 'crispy', value: 74, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 70, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '가성비' },
  },
  'chickenplus-garlic': {
    id: 129,
    name: '치킨플러스 마늘치킨',
    slug: 'chickenplus-garlic',
    brand: CHICKENPLUS,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'B',
    tier_score: 80,
    trend: 'stable',
    product_type: 'powder',
    usage: 'meal',
    price_min: 16000,
    price_max: 19000,
    review_count: 98,
    description: '치킨플러스의 마늘 치킨. 마늘 향이 가득한 시즈닝 치킨입니다.',
    release_year: 2015,
    specs: [
      { key: 'type', value: '튀김 + 마늘 시즈닝', label: '조리방식' },
      { key: 'price', value: '16,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 80, label: '맛', weight: 35 },
      { key: 'price', value: 88, label: '가성비', weight: 25 },
      { key: 'crispy', value: 78, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 74, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '가루/시즈닝', usage: '식사대용' },
  },
  'bhc-wing-king': {
    id: 130,
    name: '윙킹',
    slug: 'bhc-wing-king',
    brand: BHC,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'fried',
    usage: 'party',
    price_min: 19000,
    price_max: 22000,
    review_count: 167,
    description: 'BHC의 윙 전문 메뉴. 바삭한 닭날개가 특징입니다.',
    release_year: 2019,
    specs: [
      { key: 'type', value: '튀김', label: '조리방식' },
      { key: 'price', value: '19,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '윙 15개', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 86, label: '맛', weight: 35 },
      { key: 'price', value: 82, label: '가성비', weight: 25 },
      { key: 'crispy', value: 92, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 84, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '후라이드', usage: '치맥' },
  },
  'bbq-yangnyum': {
    id: 131,
    name: 'BBQ 양념치킨',
    slug: 'bbq-yangnyum',
    brand: BBQ,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 87,
    trend: 'stable',
    product_type: 'yangnyum',
    usage: 'party',
    price_min: 20000,
    price_max: 23000,
    review_count: 198,
    description: 'BBQ의 클래식 양념 치킨. 달콤하고 매콤한 양념이 특징입니다.',
    release_year: 2000,
    specs: [
      { key: 'type', value: '튀김 + 양념 소스', label: '조리방식' },
      { key: 'price', value: '20,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '매콤', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 88, label: '맛', weight: 35 },
      { key: 'price', value: 80, label: '가성비', weight: 25 },
      { key: 'crispy', value: 82, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 86, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '양념', usage: '파티' },
  },
  'goobne-original': {
    id: 132,
    name: '굽네 오리지널',
    slug: 'goobne-original',
    brand: GOOBNE,
    category_slug: 'chicken',
    category: CHICKEN_CATEGORY,
    image_url: '',
    tier: 'A',
    tier_score: 86,
    trend: 'stable',
    product_type: 'roasted',
    usage: 'meal',
    price_min: 18000,
    price_max: 21000,
    review_count: 234,
    description: '굽네치킨의 기본 메뉴. 담백한 오븐 구이 치킨입니다.',
    release_year: 2005,
    specs: [
      { key: 'type', value: '오븐 구이', label: '조리방식' },
      { key: 'price', value: '18,000', label: '가격', unit: '원' },
      { key: 'quantity', value: '한 마리 (약 1kg)', label: '양' },
      { key: 'spicy', value: '없음', label: '맵기' },
    ],
    scores: [
      { key: 'taste', value: 85, label: '맛', weight: 35 },
      { key: 'price', value: 84, label: '가성비', weight: 25 },
      { key: 'crispy', value: 88, label: '바삭함', weight: 20 },
      { key: 'popularity', value: 86, label: '인기도', weight: 20 },
    ],
    traps: [],
    alternatives: [],
    filter_labels: { product_type: '구이', usage: '식사대용' },
  },
};

// 통합 Mock 제품 가져오기
export function getMockProduct(slug: string): ProductDetail | null {
  return RUNNING_SHOES_PRODUCTS[slug] || CHICKEN_PRODUCTS[slug] || null;
}

// 카테고리별 Mock 제품 목록
export function getMockProductsByCategory(category: string): ProductDetail[] {
  if (category === 'running-shoes') {
    return Object.values(RUNNING_SHOES_PRODUCTS);
  }
  if (category === 'chicken') {
    return Object.values(CHICKEN_PRODUCTS);
  }
  return [];
}
