import type { Brand, Category } from '@/types/model';
import type { TierLevel } from '@/lib/tier';

// 브랜드 로고 URL 생성 함수 (Google Favicon API 활용)
const getFaviconUrl = (domain: string) => {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
};
// 런닝화 브랜드 Mock 데이터
export const RUNNING_SHOES_BRANDS: Brand[] = [
  // S티어 - 최고 브랜드
  {
    id: 1,
    name: '아식스',
    slug: 'asics',
    logo_url: getFaviconUrl('asics.com'),
    tier: 'S' as TierLevel,
    tier_score: 95.0,
    description: '일본의 러닝화 명가, 젤 쿠셔닝 기술의 선두주자',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 96 },
      { key: 'tech', label: '기술력', value: 97 },
      { key: 'durability', label: '내구성', value: 95 },
      { key: 'community', label: '커뮤니티', value: 92 },
    ],
  },
  {
    id: 2,
    name: '나이키',
    slug: 'nike',
    logo_url: getFaviconUrl('nike.com'),
    tier: 'S' as TierLevel,
    tier_score: 94.0,
    description: '세계 최대 스포츠 브랜드, 혁신적인 기술력',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 98 },
      { key: 'tech', label: '기술력', value: 96 },
      { key: 'durability', label: '내구성', value: 88 },
      { key: 'community', label: '커뮤니티', value: 95 },
    ],
  },
  {
    id: 3,
    name: '호카',
    slug: 'hoka',
    logo_url: getFaviconUrl('hoka.com'),
    tier: 'S' as TierLevel,
    tier_score: 92.5,
    description: '맥시멀 쿠셔닝의 혁명, 편안함의 대명사',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 88 },
      { key: 'tech', label: '기술력', value: 94 },
      { key: 'durability', label: '내구성', value: 90 },
      { key: 'community', label: '커뮤니티', value: 96 },
    ],
  },
  // A티어 - 우수 브랜드
  {
    id: 4,
    name: '뉴발란스',
    slug: 'new-balance',
    logo_url: getFaviconUrl('newbalance.com'),
    tier: 'A' as TierLevel,
    tier_score: 88.0,
    description: '프레시폼 기술의 선두, 안정성과 편안함',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 90 },
      { key: 'tech', label: '기술력', value: 88 },
      { key: 'durability', label: '내구성', value: 89 },
      { key: 'community', label: '커뮤니티', value: 85 },
    ],
  },
  {
    id: 5,
    name: '써코니',
    slug: 'saucony',
    logo_url: getFaviconUrl('saucony.com'),
    tier: 'A' as TierLevel,
    tier_score: 87.0,
    description: '러너들의 러너, PWRRUN 쿠셔닝 기술',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 85 },
      { key: 'tech', label: '기술력', value: 90 },
      { key: 'durability', label: '내구성', value: 88 },
      { key: 'community', label: '커뮤니티', value: 84 },
    ],
  },
  {
    id: 6,
    name: '브룩스',
    slug: 'brooks',
    logo_url: getFaviconUrl('brooksrunning.com'),
    tier: 'A' as TierLevel,
    tier_score: 86.5,
    description: 'DNA 쿠셔닝 기술, 안정화의 명가',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 84 },
      { key: 'tech', label: '기술력', value: 89 },
      { key: 'durability', label: '내구성', value: 91 },
      { key: 'community', label: '커뮤니티', value: 80 },
    ],
  },
  {
    id: 7,
    name: '아디다스',
    slug: 'adidas',
    logo_url: getFaviconUrl('adidas.com'),
    tier: 'A' as TierLevel,
    tier_score: 85.5,
    description: '부스트 폼의 원조, 독일 스포츠 명가',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 92 },
      { key: 'tech', label: '기술력', value: 86 },
      { key: 'durability', label: '내구성', value: 82 },
      { key: 'community', label: '커뮤니티', value: 83 },
    ],
  },
  // B티어 - 준수한 브랜드
  {
    id: 8,
    name: '미즈노',
    slug: 'mizuno',
    logo_url: getFaviconUrl('mizuno.com'),
    tier: 'B' as TierLevel,
    tier_score: 82.0,
    description: '웨이브 플레이트 기술, 일본 장인 정신',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 78 },
      { key: 'tech', label: '기술력', value: 85 },
      { key: 'durability', label: '내구성', value: 88 },
      { key: 'community', label: '커뮤니티', value: 76 },
    ],
  },
  {
    id: 9,
    name: '푸마',
    slug: 'puma',
    logo_url: getFaviconUrl('puma.com'),
    tier: 'B' as TierLevel,
    tier_score: 79.0,
    description: '나이트로 폼 기술, 가성비 좋은 선택',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 82 },
      { key: 'tech', label: '기술력', value: 78 },
      { key: 'durability', label: '내구성', value: 76 },
      { key: 'community', label: '커뮤니티', value: 80 },
    ],
  },
  {
    id: 10,
    name: '언더아머',
    slug: 'under-armour',
    logo_url: getFaviconUrl('underarmour.com'),
    tier: 'B' as TierLevel,
    tier_score: 77.5,
    description: 'HOVR 기술, 에너지 리턴에 강점',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 75 },
      { key: 'tech', label: '기술력', value: 80 },
      { key: 'durability', label: '내구성', value: 78 },
      { key: 'community', label: '커뮤니티', value: 77 },
    ],
  },
  {
    id: 11,
    name: '리복',
    slug: 'reebok',
    logo_url: getFaviconUrl('reebok.com'),
    tier: 'B' as TierLevel,
    tier_score: 75.0,
    description: '플로트라이드 기술, 합리적인 가격',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 72 },
      { key: 'tech', label: '기술력', value: 76 },
      { key: 'durability', label: '내구성', value: 78 },
      { key: 'community', label: '커뮤니티', value: 74 },
    ],
  },
  {
    id: 12,
    name: '온러닝',
    slug: 'on-running',
    logo_url: getFaviconUrl('on.com'),
    tier: 'A' as TierLevel,
    tier_score: 86.0,
    description: '클라우드텍 기술, 스위스 프리미엄',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 82 },
      { key: 'tech', label: '기술력', value: 91 },
      { key: 'durability', label: '내구성', value: 84 },
      { key: 'community', label: '커뮤니티', value: 87 },
    ],
  },
  // C티어 - 입문/가성비 브랜드
  {
    id: 13,
    name: '스케쳐스',
    slug: 'skechers',
    logo_url: getFaviconUrl('skechers.com'),
    tier: 'C' as TierLevel,
    tier_score: 68.0,
    description: '편안함 중심의 라이프스타일 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 70 },
      { key: 'tech', label: '기술력', value: 65 },
      { key: 'durability', label: '내구성', value: 72 },
      { key: 'community', label: '커뮤니티', value: 65 },
    ],
  },
  {
    id: 14,
    name: '데카트론',
    slug: 'decathlon',
    logo_url: getFaviconUrl('decathlon.co.kr'),
    tier: 'C' as TierLevel,
    tier_score: 65.0,
    description: 'KD900 등 가성비 좋은 입문용 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 60 },
      { key: 'tech', label: '기술력', value: 68 },
      { key: 'durability', label: '내구성', value: 70 },
      { key: 'community', label: '커뮤니티', value: 62 },
    ],
  },
  {
    id: 15,
    name: '프로스펙스',
    slug: 'prospecs',
    logo_url: getFaviconUrl('prospecs.com'),
    tier: 'C' as TierLevel,
    tier_score: 62.0,
    description: '국내 브랜드, Speed Rush 등 데일리 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 58 },
      { key: 'tech', label: '기술력', value: 62 },
      { key: 'durability', label: '내구성', value: 68 },
      { key: 'community', label: '커뮤니티', value: 60 },
    ],
  },
  {
    id: 16,
    name: '필라',
    slug: 'fila',
    logo_url: getFaviconUrl('fila.com'),
    tier: 'C' as TierLevel,
    tier_score: 60.0,
    description: '레트로 감성의 캐주얼 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 65 },
      { key: 'tech', label: '기술력', value: 55 },
      { key: 'durability', label: '내구성', value: 62 },
      { key: 'community', label: '커뮤니티', value: 58 },
    ],
  },
  {
    id: 17,
    name: '르까프',
    slug: 'le-coq-sportif',
    logo_url: getFaviconUrl('lecoqsportif.co.kr'),
    tier: 'C' as TierLevel,
    tier_score: 58.0,
    description: '프랑스 감성의 합리적 가격 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 52 },
      { key: 'tech', label: '기술력', value: 58 },
      { key: 'durability', label: '내구성', value: 65 },
      { key: 'community', label: '커뮤니티', value: 55 },
    ],
  },
  {
    id: 22,
    name: '데상트',
    slug: 'descente',
    logo_url: getFaviconUrl('descente.co.kr'),
    tier: 'C' as TierLevel,
    tier_score: 64.0,
    description: '일본 스포츠 브랜드, 합리적 가격대',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 60 },
      { key: 'tech', label: '기술력', value: 65 },
      { key: 'durability', label: '내구성', value: 68 },
      { key: 'community', label: '커뮤니티', value: 58 },
    ],
  },
  // D티어 - 비추천/입문 이하 브랜드
  {
    id: 18,
    name: '탑텐',
    slug: 'topten',
    logo_url: getFaviconUrl('topten10.co.kr'),
    tier: 'D' as TierLevel,
    tier_score: 35.0,
    description: 'SPA 브랜드의 초저가 러닝화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 30 },
      { key: 'tech', label: '기술력', value: 25 },
      { key: 'durability', label: '내구성', value: 45 },
      { key: 'community', label: '커뮤니티', value: 35 },
    ],
  },
  {
    id: 19,
    name: '에잇세컨즈',
    slug: '8seconds',
    logo_url: getFaviconUrl('ssfshop.com'),
    tier: 'D' as TierLevel,
    tier_score: 32.0,
    description: '패션 브랜드의 캐주얼 운동화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 28 },
      { key: 'tech', label: '기술력', value: 22 },
      { key: 'durability', label: '내구성', value: 40 },
      { key: 'community', label: '커뮤니티', value: 32 },
    ],
  },
  {
    id: 20,
    name: '무신사 스탠다드',
    slug: 'musinsa-standard',
    logo_url: getFaviconUrl('musinsa.com'),
    tier: 'D' as TierLevel,
    tier_score: 30.0,
    description: '패션 플랫폼의 자체 운동화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 25 },
      { key: 'tech', label: '기술력', value: 20 },
      { key: 'durability', label: '내구성', value: 38 },
      { key: 'community', label: '커뮤니티', value: 30 },
    ],
  },
  {
    id: 21,
    name: '다이소 운동화',
    slug: 'daiso',
    logo_url: getFaviconUrl('daisomall.co.kr'),
    tier: 'D' as TierLevel,
    tier_score: 20.0,
    description: '초저가 생활용품점 운동화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 15 },
      { key: 'tech', label: '기술력', value: 10 },
      { key: 'durability', label: '내구성', value: 30 },
      { key: 'community', label: '커뮤니티', value: 20 },
    ],
  },
  {
    id: 23,
    name: '스파오',
    slug: 'spao',
    logo_url: getFaviconUrl('spao.com'),
    tier: 'D' as TierLevel,
    tier_score: 32.0,
    description: 'SPA 브랜드의 저가형 운동화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 25 },
      { key: 'tech', label: '기술력', value: 20 },
      { key: 'durability', label: '내구성', value: 42 },
      { key: 'community', label: '커뮤니티', value: 35 },
    ],
  },
  {
    id: 24,
    name: '노브랜드',
    slug: 'nobrand',
    logo_url: getFaviconUrl('emart.com'),
    tier: 'D' as TierLevel,
    tier_score: 30.0,
    description: '이마트 PB 브랜드 초저가 운동화',
    category: 'running-shoes',
    scores: [
      { key: 'lineup', label: '라인업', value: 22 },
      { key: 'tech', label: '기술력', value: 18 },
      { key: 'durability', label: '내구성', value: 38 },
      { key: 'community', label: '커뮤니티', value: 28 },
    ],
  },
];

// 런닝화 카테고리 정보
export const RUNNING_SHOES_CATEGORY: Category = {
  id: 1,
  slug: 'running-shoes',
  name: '러닝화',
  description: '러닝화 브랜드 계급도 - 커뮤니티 리뷰 기반',
  icon: '👟',
  display_order: 1,
  is_active: true,
  spec_definitions: [
    { key: 'weight', label: '무게', unit: 'g', type: 'number' },
    { key: 'stack_height', label: '스택 높이', unit: 'mm', type: 'number' },
    { key: 'drop', label: '드롭', unit: 'mm', type: 'number' },
    { key: 'upper', label: '어퍼 소재', type: 'text' },
    { key: 'midsole', label: '미드솔', type: 'text' },
  ],
  score_definitions: [
    { key: 'cushion', label: '쿠셔닝', weight: 25 },
    { key: 'responsiveness', label: '반응성', weight: 25 },
    { key: 'stability', label: '안정성', weight: 25 },
    { key: 'durability', label: '내구성', weight: 25 },
  ],
  brand_score_definitions: [
    { key: 'lineup', label: '라인업 점수', weight: 25 },
    { key: 'tech', label: '기술력 점수', weight: 30 },
    { key: 'durability', label: '내구성 점수', weight: 25 },
    { key: 'community', label: '커뮤니티 점수', weight: 20 },
  ],
  filter_definitions: {
    product_type: [
      { value: 'cushion', label: '쿠션화' },
      { value: 'stability', label: '안정화' },
      { value: 'racing', label: '레이싱화' },
    ],
    usage: [
      { value: 'daily', label: '데일리 러닝' },
      { value: 'long', label: '장거리' },
      { value: 'race', label: '레이스' },
    ],
  },
  quiz_definitions: [
    {
      key: 'budget',
      question: '예산은 어느 정도인가요?',
      emoji: '💰',
      options: [
        { value: 'low', label: '10만원 이하', description: '가성비 중시' },
        { value: 'mid', label: '10-20만원', description: '적당한 투자' },
        { value: 'high', label: '20만원 이상', description: '최고급 제품' },
      ],
    },
    {
      key: 'usage',
      question: '주로 어떤 용도로 사용하시나요?',
      emoji: '🏃',
      options: [
        { value: 'beginner', label: '입문/취미', description: '가볍게 달리기' },
        { value: 'daily', label: '일상 훈련', description: '꾸준한 러닝' },
        { value: 'race', label: '대회/레이스', description: '기록 도전' },
      ],
    },
    {
      key: 'foot_type',
      question: '발 모양은 어떤가요?',
      emoji: '🦶',
      options: [
        { value: 'flat', label: '평발', description: '아치가 낮음' },
        { value: 'normal', label: '보통', description: '일반적인 아치' },
        { value: 'high', label: '요족', description: '아치가 높음' },
      ],
    },
    {
      key: 'priority',
      question: '가장 중요하게 생각하는 것은?',
      emoji: '⭐',
      options: [
        { value: 'cushion', label: '쿠셔닝', description: '편안함 우선' },
        { value: 'speed', label: '경량성', description: '빠른 속도' },
        { value: 'stability', label: '안정성', description: '부상 방지' },
      ],
    },
  ],
};

// 치킨 브랜드 로고 맵 (Google Favicon API 활용)
const CHICKEN_BRAND_LOGOS: Record<string, string> = {
  'BBQ': getFaviconUrl('bbq.co.kr'),
  '교촌': getFaviconUrl('kyochon.com'),
  'BHC': getFaviconUrl('bhc.co.kr'),
  '굽네': getFaviconUrl('goobne.co.kr'),
  '네네': getFaviconUrl('nenechicken.com'),
  '푸라닭': getFaviconUrl('puradak.co.kr'),
  '처갓집': getFaviconUrl('cheogajip.co.kr'),
  '페리카나': getFaviconUrl('pelicana.co.kr'),
  '호식이': getFaviconUrl('hosigi.com'),
  '멕시카나': getFaviconUrl('mexicana.co.kr'),
};

// 치킨 프랜차이즈(브랜드) Mock 데이터
export const CHICKEN_BRANDS: Brand[] = [
  // S티어 — 황제 (프랜차이즈)
  {
    id: 201,
    name: 'BBQ',
    slug: 'bbq',
    logo_url: CHICKEN_BRAND_LOGOS['BBQ'],
    tier: 'S' as TierLevel,
    tier_score: 94.5,
    description: '황금올리브치킨의 BBQ, 올리브유 치킨의 원조',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 95 },
      { key: 'price', label: '가성비', value: 82 },
      { key: 'variety', label: '메뉴 다양성', value: 92 },
      { key: 'accessibility', label: '접근성', value: 95 },
    ],
  },
  {
    id: 202,
    name: 'BHC',
    slug: 'bhc',
    logo_url: CHICKEN_BRAND_LOGOS['BHC'],
    tier: 'S' as TierLevel,
    tier_score: 93.0,
    description: '뿌링클, 맛초킹의 BHC, MZ세대 인기 1위',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 93 },
      { key: 'price', label: '가성비', value: 80 },
      { key: 'variety', label: '메뉴 다양성', value: 95 },
      { key: 'accessibility', label: '접근성', value: 92 },
    ],
  },
  {
    id: 203,
    name: '교촌치킨',
    slug: 'kyochon',
    logo_url: CHICKEN_BRAND_LOGOS['교촌'],
    tier: 'S' as TierLevel,
    tier_score: 92.5,
    description: '간장 치킨의 명가, 프리미엄 치킨의 대명사',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 94 },
      { key: 'price', label: '가성비', value: 78 },
      { key: 'variety', label: '메뉴 다양성', value: 88 },
      { key: 'accessibility', label: '접근성', value: 90 },
    ],
  },
  // A티어 — 왕
  {
    id: 204,
    name: '굽네치킨',
    slug: 'goobne',
    logo_url: CHICKEN_BRAND_LOGOS['굽네'],
    tier: 'A' as TierLevel,
    tier_score: 87.5,
    description: '오븐구이 치킨의 선두주자, 건강한 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 88 },
      { key: 'price', label: '가성비', value: 80 },
      { key: 'variety', label: '메뉴 다양성', value: 85 },
      { key: 'accessibility', label: '접근성', value: 88 },
    ],
  },
  {
    id: 205,
    name: '네네치킨',
    slug: 'nene',
    logo_url: CHICKEN_BRAND_LOGOS['네네'],
    tier: 'A' as TierLevel,
    tier_score: 86.5,
    description: '스노윙 치킨의 네네, 다양한 시즈닝',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 85 },
      { key: 'price', label: '가성비', value: 82 },
      { key: 'variety', label: '메뉴 다양성', value: 90 },
      { key: 'accessibility', label: '접근성', value: 85 },
    ],
  },
  {
    id: 206,
    name: '푸라닭',
    slug: 'puradak',
    logo_url: CHICKEN_BRAND_LOGOS['푸라닭'],
    tier: 'A' as TierLevel,
    tier_score: 85.0,
    description: '블랙알리오의 푸라닭, 프리미엄 마늘 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 90 },
      { key: 'price', label: '가성비', value: 72 },
      { key: 'variety', label: '메뉴 다양성', value: 78 },
      { key: 'accessibility', label: '접근성', value: 80 },
    ],
  },
  // B티어 — 양반
  {
    id: 207,
    name: '호식이두마리치킨',
    slug: 'hosigi',
    logo_url: CHICKEN_BRAND_LOGOS['호식이'],
    tier: 'B' as TierLevel,
    tier_score: 82.0,
    description: '두마리 치킨의 원조, 가성비 최강',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 78 },
      { key: 'price', label: '가성비', value: 95 },
      { key: 'variety', label: '메뉴 다양성', value: 75 },
      { key: 'accessibility', label: '접근성', value: 82 },
    ],
  },
  {
    id: 208,
    name: '처갓집양념치킨',
    slug: 'cheogajip',
    logo_url: CHICKEN_BRAND_LOGOS['처갓집'],
    tier: 'B' as TierLevel,
    tier_score: 80.5,
    description: '전통 양념 치킨의 명가',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 82 },
      { key: 'price', label: '가성비', value: 78 },
      { key: 'variety', label: '메뉴 다양성', value: 72 },
      { key: 'accessibility', label: '접근성', value: 78 },
    ],
  },
  {
    id: 209,
    name: '60계치킨',
    slug: '60gye',
    logo_url: getFaviconUrl('60gye.co.kr'),
    tier: 'B' as TierLevel,
    tier_score: 79.0,
    description: '6천원대 치킨의 시작, 가성비 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 75 },
      { key: 'price', label: '가성비', value: 98 },
      { key: 'variety', label: '메뉴 다양성', value: 70 },
      { key: 'accessibility', label: '접근성', value: 85 },
    ],
  },
  {
    id: 210,
    name: 'KFC',
    slug: 'kfc',
    logo_url: getFaviconUrl('kfc.co.kr'),
    tier: 'B' as TierLevel,
    tier_score: 78.0,
    description: '오리지널 레시피의 KFC, 글로벌 치킨 브랜드',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛 평균', value: 80 },
      { key: 'price', label: '가성비', value: 70 },
      { key: 'variety', label: '메뉴 다양성', value: 80 },
      { key: 'accessibility', label: '접근성', value: 92 },
    ],
  },
];

// 치킨 메뉴(제품) Mock 데이터 (브랜드별 대표 메뉴)
export const CHICKEN_MENUS: Brand[] = [
  // S티어 - 최고 인기 메뉴
  {
    id: 101,
    name: '황금올리브치킨',
    slug: 'bbq-golden-olive',
    logo_url: CHICKEN_BRAND_LOGOS['BBQ'],
    brand_name: 'BBQ',
    tier: 'S' as TierLevel,
    tier_score: 94.5,
    description: 'BBQ의 시그니처 메뉴, 올리브유로 튀긴 바삭한 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 96 },
      { key: 'price', label: '가성비', value: 88 },
      { key: 'crispy', label: '바삭함', value: 95 },
      { key: 'popularity', label: '인기도', value: 98 },
    ],
  },
  {
    id: 102,
    name: '교촌 오리지날',
    slug: 'kyochon-original',
    logo_url: CHICKEN_BRAND_LOGOS['교촌'],
    brand_name: '교촌',
    tier: 'S' as TierLevel,
    tier_score: 93.0,
    description: '교촌치킨의 간장 소스 오리지널 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 95 },
      { key: 'price', label: '가성비', value: 85 },
      { key: 'crispy', label: '바삭함', value: 90 },
      { key: 'popularity', label: '인기도', value: 96 },
    ],
  },
  {
    id: 103,
    name: '뿌링클',
    slug: 'bhc-puringkle',
    logo_url: CHICKEN_BRAND_LOGOS['BHC'],
    brand_name: 'BHC',
    tier: 'S' as TierLevel,
    tier_score: 92.5,
    description: 'BHC의 치즈 시즈닝 치킨, MZ세대 인기',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 94 },
      { key: 'price', label: '가성비', value: 86 },
      { key: 'crispy', label: '바삭함', value: 92 },
      { key: 'popularity', label: '인기도', value: 97 },
    ],
  },
  // A티어 - 우수 메뉴
  {
    id: 104,
    name: '교촌 레드',
    slug: 'kyochon-red',
    logo_url: CHICKEN_BRAND_LOGOS['교촌'],
    brand_name: '교촌',
    tier: 'A' as TierLevel,
    tier_score: 88.5,
    description: '교촌의 매콤한 양념 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 90 },
      { key: 'price', label: '가성비', value: 84 },
      { key: 'crispy', label: '바삭함', value: 88 },
      { key: 'popularity', label: '인기도', value: 91 },
    ],
  },
  {
    id: 105,
    name: '굽네 고추바사삭',
    slug: 'goobne-gochu',
    logo_url: CHICKEN_BRAND_LOGOS['굽네'],
    brand_name: '굽네',
    tier: 'A' as TierLevel,
    tier_score: 87.0,
    description: '굽네의 오븐구이 매콤 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 89 },
      { key: 'price', label: '가성비', value: 82 },
      { key: 'crispy', label: '바삭함', value: 86 },
      { key: 'popularity', label: '인기도', value: 90 },
    ],
  },
  {
    id: 106,
    name: '네네 스노윙',
    slug: 'nene-snowing',
    logo_url: CHICKEN_BRAND_LOGOS['네네'],
    brand_name: '네네',
    tier: 'A' as TierLevel,
    tier_score: 86.5,
    description: '네네치킨의 눈꽃 치즈 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 88 },
      { key: 'price', label: '가성비', value: 83 },
      { key: 'crispy', label: '바삭함', value: 85 },
      { key: 'popularity', label: '인기도', value: 89 },
    ],
  },
  {
    id: 107,
    name: '푸라닭 블랙알리오',
    slug: 'puradak-black-allio',
    logo_url: CHICKEN_BRAND_LOGOS['푸라닭'],
    brand_name: '푸라닭',
    tier: 'A' as TierLevel,
    tier_score: 86.0,
    description: '푸라닭의 마늘 풍미 프리미엄 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 90 },
      { key: 'price', label: '가성비', value: 75 },
      { key: 'crispy', label: '바삭함', value: 88 },
      { key: 'popularity', label: '인기도', value: 88 },
    ],
  },
  {
    id: 108,
    name: 'BBQ 자메이카 통다리',
    slug: 'bbq-jamaica',
    logo_url: CHICKEN_BRAND_LOGOS['BBQ'],
    brand_name: 'BBQ',
    tier: 'A' as TierLevel,
    tier_score: 85.5,
    description: 'BBQ의 저크 시즈닝 통다리 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 87 },
      { key: 'price', label: '가성비', value: 80 },
      { key: 'crispy', label: '바삭함', value: 86 },
      { key: 'popularity', label: '인기도', value: 88 },
    ],
  },
  {
    id: 109,
    name: '맛초킹',
    slug: 'bhc-matchoking',
    logo_url: CHICKEN_BRAND_LOGOS['BHC'],
    brand_name: 'BHC',
    tier: 'A' as TierLevel,
    tier_score: 85.0,
    description: 'BHC의 매콤달콤 양념 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 87 },
      { key: 'price', label: '가성비', value: 82 },
      { key: 'crispy', label: '바삭함', value: 84 },
      { key: 'popularity', label: '인기도', value: 86 },
    ],
  },
  // B티어 - 준수한 메뉴
  {
    id: 110,
    name: '굽네 볼케이노',
    slug: 'goobne-volcano',
    logo_url: CHICKEN_BRAND_LOGOS['굽네'],
    brand_name: '굽네',
    tier: 'B' as TierLevel,
    tier_score: 82.0,
    description: '굽네의 매운맛 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 84 },
      { key: 'price', label: '가성비', value: 80 },
      { key: 'crispy', label: '바삭함', value: 82 },
      { key: 'popularity', label: '인기도', value: 82 },
    ],
  },
  {
    id: 111,
    name: '처갓집 슈프림양념',
    slug: 'cheogajip-supreme',
    logo_url: CHICKEN_BRAND_LOGOS['처갓집'],
    brand_name: '처갓집',
    tier: 'B' as TierLevel,
    tier_score: 80.5,
    description: '처갓집의 대표 양념 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 82 },
      { key: 'price', label: '가성비', value: 85 },
      { key: 'crispy', label: '바삭함', value: 78 },
      { key: 'popularity', label: '인기도', value: 78 },
    ],
  },
  {
    id: 112,
    name: '페리카나 양념치킨',
    slug: 'pelicana-yangnyum',
    logo_url: CHICKEN_BRAND_LOGOS['페리카나'],
    brand_name: '페리카나',
    tier: 'B' as TierLevel,
    tier_score: 79.5,
    description: '페리카나의 클래식 양념 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 81 },
      { key: 'price', label: '가성비', value: 84 },
      { key: 'crispy', label: '바삭함', value: 76 },
      { key: 'popularity', label: '인기도', value: 77 },
    ],
  },
  {
    id: 113,
    name: '호식이 후라이드',
    slug: 'hosigi-fried',
    logo_url: CHICKEN_BRAND_LOGOS['호식이'],
    brand_name: '호식이',
    tier: 'B' as TierLevel,
    tier_score: 78.0,
    description: '호식이의 가성비 후라이드',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 78 },
      { key: 'price', label: '가성비', value: 95 },
      { key: 'crispy', label: '바삭함', value: 75 },
      { key: 'popularity', label: '인기도', value: 72 },
    ],
  },
  {
    id: 114,
    name: '멕시카나 반반치킨',
    slug: 'mexicana-half',
    logo_url: CHICKEN_BRAND_LOGOS['멕시카나'],
    brand_name: '멕시카나',
    tier: 'B' as TierLevel,
    tier_score: 77.0,
    description: '멕시카나의 후라이드+양념 조합',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 78 },
      { key: 'price', label: '가성비', value: 82 },
      { key: 'crispy', label: '바삭함', value: 76 },
      { key: 'popularity', label: '인기도', value: 73 },
    ],
  },
  // C티어 - 평범한 메뉴
  {
    id: 115,
    name: '60계 후라이드',
    slug: '60gye-fried',
    logo_url: getFaviconUrl('60gye.co.kr'),
    brand_name: '60계치킨',
    tier: 'C' as TierLevel,
    tier_score: 68.0,
    description: '60계치킨의 기본 후라이드',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 70 },
      { key: 'price', label: '가성비', value: 88 },
      { key: 'crispy', label: '바삭함', value: 68 },
      { key: 'popularity', label: '인기도', value: 65 },
    ],
  },
  {
    id: 116,
    name: '노랑통닭 후라이드',
    slug: 'norang-fried',
    logo_url: getFaviconUrl('norangtongdak.com'),
    brand_name: '노랑통닭',
    tier: 'C' as TierLevel,
    tier_score: 65.0,
    description: '노랑통닭의 클래식 후라이드',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 68 },
      { key: 'price', label: '가성비', value: 90 },
      { key: 'crispy', label: '바삭함', value: 65 },
      { key: 'popularity', label: '인기도', value: 60 },
    ],
  },
  {
    id: 117,
    name: '가마치통닭',
    slug: 'gamachi-fried',
    logo_url: getFaviconUrl('gamachi.co.kr'),
    brand_name: '가마치통닭',
    tier: 'C' as TierLevel,
    tier_score: 62.0,
    description: '가마솥에 튀긴 전통 방식 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 65 },
      { key: 'price', label: '가성비', value: 85 },
      { key: 'crispy', label: '바삭함', value: 62 },
      { key: 'popularity', label: '인기도', value: 58 },
    ],
  },
  {
    id: 118,
    name: '자담치킨 순살',
    slug: 'jadam-boneless',
    logo_url: getFaviconUrl('jadamchicken.com'),
    brand_name: '자담치킨',
    tier: 'C' as TierLevel,
    tier_score: 60.0,
    description: '자담치킨의 순살 메뉴',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 62 },
      { key: 'price', label: '가성비', value: 78 },
      { key: 'crispy', label: '바삭함', value: 60 },
      { key: 'popularity', label: '인기도', value: 55 },
    ],
  },
  {
    id: 119,
    name: '또래오래 후라이드',
    slug: 'ttoraeore-fried',
    logo_url: getFaviconUrl('ttoraeore.co.kr'),
    brand_name: '또래오래',
    tier: 'C' as TierLevel,
    tier_score: 58.0,
    description: '또래오래의 가성비 후라이드',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 60 },
      { key: 'price', label: '가성비', value: 92 },
      { key: 'crispy', label: '바삭함', value: 58 },
      { key: 'popularity', label: '인기도', value: 52 },
    ],
  },
  {
    id: 124,
    name: '지코바 숯불양념',
    slug: 'zicoba-charcoal',
    logo_url: getFaviconUrl('zicoba.co.kr'),
    brand_name: '지코바',
    tier: 'C' as TierLevel,
    tier_score: 66.0,
    description: '숯불로 구운 양념구이 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 72 },
      { key: 'price', label: '가성비', value: 75 },
      { key: 'crispy', label: '바삭함', value: 60 },
      { key: 'popularity', label: '인기도', value: 58 },
    ],
  },
  {
    id: 125,
    name: '땅땅치킨 후라이드',
    slug: 'ddangddang-fried',
    logo_url: getFaviconUrl('ddangddang.co.kr'),
    brand_name: '땅땅치킨',
    tier: 'C' as TierLevel,
    tier_score: 56.0,
    description: '저렴한 가격의 땅땅치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 58 },
      { key: 'price', label: '가성비', value: 90 },
      { key: 'crispy', label: '바삭함', value: 55 },
      { key: 'popularity', label: '인기도', value: 48 },
    ],
  },
  {
    id: 126,
    name: '피자나라치킨공주 후라이드',
    slug: 'pizzanara-fried',
    logo_url: getFaviconUrl('pizzanara.co.kr'),
    brand_name: '피자나라치킨공주',
    tier: 'C' as TierLevel,
    tier_score: 55.0,
    description: '피자와 치킨을 함께 시킬 수 있는 가성비 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 55 },
      { key: 'price', label: '가성비', value: 88 },
      { key: 'crispy', label: '바삭함', value: 52 },
      { key: 'popularity', label: '인기도', value: 50 },
    ],
  },
  {
    id: 127,
    name: '큰통치킨 후라이드',
    slug: 'bigchicken-fried',
    logo_url: getFaviconUrl('bigchicken.co.kr'),
    brand_name: '큰통치킨',
    tier: 'C' as TierLevel,
    tier_score: 64.0,
    description: '가성비 좋은 큰 통닭',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 68 },
      { key: 'price', label: '가성비', value: 85 },
      { key: 'crispy', label: '바삭함', value: 62 },
      { key: 'popularity', label: '인기도', value: 55 },
    ],
  },
  // D티어 - 비추천 메뉴
  {
    id: 120,
    name: '편의점 치킨',
    slug: 'convenience-chicken',
    logo_url: getFaviconUrl('cu.co.kr'),
    brand_name: 'CU/GS25',
    tier: 'D' as TierLevel,
    tier_score: 35.0,
    description: '편의점 즉석 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 40 },
      { key: 'price', label: '가성비', value: 60 },
      { key: 'crispy', label: '바삭함', value: 30 },
      { key: 'popularity', label: '인기도', value: 25 },
    ],
  },
  {
    id: 121,
    name: '마트 치킨',
    slug: 'mart-chicken',
    logo_url: getFaviconUrl('emart.com'),
    brand_name: '이마트/홈플러스',
    tier: 'D' as TierLevel,
    tier_score: 38.0,
    description: '대형마트 델리 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 45 },
      { key: 'price', label: '가성비', value: 75 },
      { key: 'crispy', label: '바삭함', value: 35 },
      { key: 'popularity', label: '인기도', value: 30 },
    ],
  },
  {
    id: 122,
    name: '냉동 치킨',
    slug: 'frozen-chicken',
    logo_url: getFaviconUrl('cj.co.kr'),
    brand_name: '비비고/풀무원',
    tier: 'D' as TierLevel,
    tier_score: 32.0,
    description: '에어프라이어용 냉동 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 38 },
      { key: 'price', label: '가성비', value: 70 },
      { key: 'crispy', label: '바삭함', value: 32 },
      { key: 'popularity', label: '인기도', value: 28 },
    ],
  },
  {
    id: 123,
    name: '학교 급식 치킨',
    slug: 'school-chicken',
    logo_url: getFaviconUrl('naver.com'),
    brand_name: '급식',
    tier: 'D' as TierLevel,
    tier_score: 25.0,
    description: '학교/기업 급식용 치킨',
    category: 'chicken',
    scores: [
      { key: 'taste', label: '맛', value: 30 },
      { key: 'price', label: '가성비', value: 95 },
      { key: 'crispy', label: '바삭함', value: 20 },
      { key: 'popularity', label: '인기도', value: 15 },
    ],
  },
];

// 치킨 카테고리 정보
export const CHICKEN_CATEGORY: Category = {
  id: 2,
  slug: 'chicken',
  name: '치킨',
  description: '대한민국 치킨 메뉴 계급도',
  icon: '🍗',
  display_order: 2,
  is_active: true,
  spec_definitions: [
    { key: 'brand', label: '브랜드', type: 'text' },
    { key: 'price', label: '가격', unit: '원', type: 'number' },
    { key: 'type', label: '조리방식', type: 'select', options: [
      { value: 'fried', label: '후라이드' },
      { value: 'seasoned', label: '양념' },
      { value: 'roasted', label: '구이' },
    ]},
  ],
  score_definitions: [
    { key: 'taste', label: '맛', weight: 35 },
    { key: 'price', label: '가성비', weight: 25 },
    { key: 'crispy', label: '바삭함', weight: 20 },
    { key: 'popularity', label: '인기도', weight: 20 },
  ],
  brand_score_definitions: [
    { key: 'taste', label: '맛', weight: 35 },
    { key: 'price', label: '가성비', weight: 25 },
    { key: 'crispy', label: '바삭함', weight: 20 },
    { key: 'popularity', label: '인기도', weight: 20 },
  ],
  filter_definitions: {
    product_type: [
      { value: 'fried', label: '후라이드' },
      { value: 'seasoned', label: '양념' },
      { value: 'roasted', label: '구이' },
    ],
    usage: [
      { value: 'alone', label: '혼닭' },
      { value: 'party', label: '파티' },
      { value: 'meal', label: '식사 대용' },
    ],
  },
  quiz_definitions: [
    {
      key: 'flavor',
      question: '어떤 맛을 좋아하시나요?',
      emoji: '👅',
      options: [
        { value: 'original', label: '담백한 후라이드', description: '치킨 본연의 맛' },
        { value: 'sweet', label: '달콤한 양념', description: '달콤짭짤한 맛' },
        { value: 'spicy', label: '매콤한 맛', description: '칼칼하게 매운 맛' },
        { value: 'garlic', label: '마늘/간장 맛', description: '감칠맛 나는 풍미' },
      ],
    },
    {
      key: 'occasion',
      question: '어떤 상황에서 먹으시나요?',
      emoji: '🎉',
      options: [
        { value: 'alone', label: '혼자 먹을 때', description: '혼닭 타임' },
        { value: 'couple', label: '연인/친구와', description: '2~3명이서' },
        { value: 'party', label: '모임/파티', description: '여러 명이 함께' },
        { value: 'meal', label: '식사 대용', description: '든든한 한 끼' },
      ],
    },
    {
      key: 'drink',
      question: '함께 마실 음료는?',
      emoji: '🍺',
      options: [
        { value: 'beer', label: '맥주', description: '치맥은 진리' },
        { value: 'soju', label: '소주', description: '치소도 좋지' },
        { value: 'coke', label: '콜라/사이다', description: '탄산과 함께' },
        { value: 'none', label: '음료 없이', description: '치킨만으로 충분' },
      ],
    },
    {
      key: 'texture',
      question: '선호하는 식감은?',
      emoji: '✨',
      options: [
        { value: 'crispy', label: '바삭바삭', description: '크리스피한 튀김옷' },
        { value: 'juicy', label: '촉촉한 육즙', description: '부드러운 살코기' },
        { value: 'chewy', label: '쫄깃한 식감', description: '씹는 맛이 있는' },
        { value: 'any', label: '상관없음', description: '맛있으면 OK' },
      ],
    },
    {
      key: 'price',
      question: '예산은 어느 정도인가요?',
      emoji: '💰',
      options: [
        { value: 'cheap', label: '2만원 이하', description: '가성비 최고' },
        { value: 'normal', label: '2~2.5만원', description: '적당한 가격' },
        { value: 'premium', label: '2.5만원 이상', description: '프리미엄 치킨' },
      ],
    },
  ],
};

// 치킨 퀴즈 추천 결과
export const CHICKEN_RECOMMENDATIONS = {
  // 후라이드 + 혼닭 + 맥주
  'original_alone_beer': [
    { slug: 'bbq-golden-olive', name: '황금올리브치킨', brand: 'BBQ', match: 95, reason: '혼자 즐기기 좋은 바삭한 프리미엄 후라이드' },
    { slug: 'kyochon-original', name: '교촌 오리지날', brand: '교촌', match: 90, reason: '담백한 간장 풍미의 클래식' },
    { slug: 'hosigi-fried', name: '호식이 후라이드', brand: '호식이', match: 85, reason: '가성비 좋은 든든한 선택' },
  ],
  // 양념 + 파티 + 맥주
  'sweet_party_beer': [
    { slug: 'bhc-puringkle', name: '뿌링클', brand: 'BHC', match: 96, reason: '모임에서 인기 폭발, 치즈 시즈닝의 매력' },
    { slug: 'kyochon-red', name: '교촌 레드', brand: '교촌', match: 88, reason: '달콤매콤, 누구나 좋아하는 맛' },
    { slug: 'nene-snowing', name: '네네 스노윙', brand: '네네', match: 85, reason: '눈꽃 치즈로 파티 분위기 UP' },
  ],
  // 매운맛 + 소주
  'spicy_couple_soju': [
    { slug: 'goobne-gochu', name: '굽네 고추바사삭', brand: '굽네', match: 94, reason: '칼칼한 매운맛에 소주가 술술' },
    { slug: 'bhc-matchoking', name: '맛초킹', brand: 'BHC', match: 89, reason: '매콤달콤 중독성 있는 맛' },
    { slug: 'cheogajip-supreme', name: '처갓집 슈프림양념', brand: '처갓집', match: 82, reason: '진한 양념의 매력' },
  ],
  // 마늘/간장 + 식사대용
  'garlic_meal_none': [
    { slug: 'puradak-black-allio', name: '푸라닭 블랙알리오', brand: '푸라닭', match: 97, reason: '마늘 풍미 가득, 든든한 한 끼' },
    { slug: 'kyochon-original', name: '교촌 오리지날', brand: '교촌', match: 91, reason: '간장 베이스의 깊은 맛' },
    { slug: 'bbq-jamaica', name: 'BBQ 자메이카 통다리', brand: 'BBQ', match: 86, reason: '풍부한 향신료의 이국적 맛' },
  ],
  // 기본 추천 (fallback)
  'default': [
    { slug: 'bbq-golden-olive', name: '황금올리브치킨', brand: 'BBQ', match: 92, reason: '대한민국 대표 치킨, 모두가 인정하는 맛' },
    { slug: 'bhc-puringkle', name: '뿌링클', brand: 'BHC', match: 88, reason: 'MZ세대 인기 1위, 중독성 있는 치즈맛' },
    { slug: 'kyochon-original', name: '교촌 오리지날', brand: '교촌', match: 85, reason: '간장치킨의 원조, 변함없는 클래식' },
  ],
};

// ==========================================
// 남자시계 카테고리 데이터
// ==========================================

// 시계 브랜드 로고 URL
const WATCH_BRAND_LOGOS: Record<string, string> = {
  '파텍 필립': getFaviconUrl('patek.com'),
  '바쉐론 콘스탄틴': getFaviconUrl('vacheron-constantin.com'),
  '오데마 피게': getFaviconUrl('audemarspiguet.com'),
  '아 랑에 운트 죄네': getFaviconUrl('alange-soehne.com'),
  '브레게': getFaviconUrl('breguet.com'),
  '롤렉스': getFaviconUrl('rolex.com'),
  '예거 르쿨트르': getFaviconUrl('jaeger-lecoultre.com'),
  '블랑팡': getFaviconUrl('blancpain.com'),
  '피아제': getFaviconUrl('piaget.com'),
  '오메가': getFaviconUrl('omegawatches.com'),
  '까르띠에': getFaviconUrl('cartier.com'),
  'IWC': getFaviconUrl('iwc.com'),
  '파네라이': getFaviconUrl('panerai.com'),
  '그랜드 세이코': getFaviconUrl('grand-seiko.com'),
  '태그호이어': getFaviconUrl('tagheuer.com'),
  '튜더': getFaviconUrl('tudorwatch.com'),
  '론진': getFaviconUrl('longines.com'),
  '브라이틀링': getFaviconUrl('breitling.com'),
  '노모스': getFaviconUrl('nomos-glashuette.com'),
  '티쏘': getFaviconUrl('tissotwatches.com'),
  '해밀턴': getFaviconUrl('hamiltonwatch.com'),
  '세이코': getFaviconUrl('seikowatches.com'),
  '카시오': getFaviconUrl('casio.com'),
  '애플': getFaviconUrl('apple.com'),
};

export const WATCH_BRANDS: Brand[] = [
  // S티어 — 황제 (하이엔드 빅5)
  {
    id: 301,
    name: '파텍 필립',
    slug: 'patek-philippe',
    logo_url: WATCH_BRAND_LOGOS['파텍 필립'],
    tier: 'S' as TierLevel,
    tier_score: 99.0,
    description: '시계의 왕, 다음 세대를 위해 보관하는 시계',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 100 },
      { key: 'craftsmanship', label: '기술력', value: 100 },
      { key: 'resale', label: '환금성', value: 98 },
      { key: 'prestige', label: '브랜드 가치', value: 100 },
    ],
  },
  {
    id: 302,
    name: '바쉐론 콘스탄틴',
    slug: 'vacheron-constantin',
    logo_url: WATCH_BRAND_LOGOS['바쉐론 콘스탄틴'],
    tier: 'S' as TierLevel,
    tier_score: 98.0,
    description: '1755년 창립, 세계에서 가장 오래된 시계 매뉴팩처',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 100 },
      { key: 'craftsmanship', label: '기술력', value: 99 },
      { key: 'resale', label: '환금성', value: 95 },
      { key: 'prestige', label: '브랜드 가치', value: 98 },
    ],
  },
  {
    id: 303,
    name: '오데마 피게',
    slug: 'audemars-piguet',
    logo_url: WATCH_BRAND_LOGOS['오데마 피게'],
    tier: 'S' as TierLevel,
    tier_score: 97.5,
    description: '로열 오크의 전설, 럭셔리 스포츠워치의 시작',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 96 },
      { key: 'craftsmanship', label: '기술력', value: 98 },
      { key: 'resale', label: '환금성', value: 97 },
      { key: 'prestige', label: '브랜드 가치', value: 99 },
    ],
  },
  {
    id: 304,
    name: '아 랑에 운트 죄네',
    slug: 'a-lange-soehne',
    logo_url: WATCH_BRAND_LOGOS['아 랑에 운트 죄네'],
    tier: 'S' as TierLevel,
    tier_score: 97.0,
    description: '독일 시계 제조의 정수, 완벽한 마감의 대명사',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 95 },
      { key: 'craftsmanship', label: '기술력', value: 100 },
      { key: 'resale', label: '환금성', value: 93 },
      { key: 'prestige', label: '브랜드 가치', value: 97 },
    ],
  },
  {
    id: 305,
    name: '브레게',
    slug: 'breguet',
    logo_url: WATCH_BRAND_LOGOS['브레게'],
    tier: 'S' as TierLevel,
    tier_score: 96.0,
    description: '시계 역사의 아버지, 투르비용의 발명자',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 100 },
      { key: 'craftsmanship', label: '기술력', value: 97 },
      { key: 'resale', label: '환금성', value: 90 },
      { key: 'prestige', label: '브랜드 가치', value: 96 },
    ],
  },
  // A티어 — 왕 (탑클래스 럭셔리)
  {
    id: 306,
    name: '롤렉스',
    slug: 'rolex',
    logo_url: WATCH_BRAND_LOGOS['롤렉스'],
    tier: 'A' as TierLevel,
    tier_score: 95.0,
    description: '시계질의 끝은 결돌롤, 압도적 대중 인지도와 환금성',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 95 },
      { key: 'craftsmanship', label: '기술력', value: 92 },
      { key: 'resale', label: '환금성', value: 100 },
      { key: 'prestige', label: '브랜드 가치', value: 98 },
    ],
  },
  {
    id: 307,
    name: '예거 르쿨트르',
    slug: 'jaeger-lecoultre',
    logo_url: WATCH_BRAND_LOGOS['예거 르쿨트르'],
    tier: 'A' as TierLevel,
    tier_score: 93.0,
    description: '시계 제조사들의 시계 제조사, 1,400개 이상의 칼리버',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 97 },
      { key: 'craftsmanship', label: '기술력', value: 98 },
      { key: 'resale', label: '환금성', value: 85 },
      { key: 'prestige', label: '브랜드 가치', value: 93 },
    ],
  },
  {
    id: 308,
    name: '블랑팡',
    slug: 'blancpain',
    logo_url: WATCH_BRAND_LOGOS['블랑팡'],
    tier: 'A' as TierLevel,
    tier_score: 92.0,
    description: '1735년 창립, 세계 최초의 시계 브랜드',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 98 },
      { key: 'craftsmanship', label: '기술력', value: 95 },
      { key: 'resale', label: '환금성', value: 83 },
      { key: 'prestige', label: '브랜드 가치', value: 91 },
    ],
  },
  {
    id: 309,
    name: '피아제',
    slug: 'piaget',
    logo_url: WATCH_BRAND_LOGOS['피아제'],
    tier: 'A' as TierLevel,
    tier_score: 91.0,
    description: '초박형 무브먼트의 선구자, 주얼리워치의 명가',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 92 },
      { key: 'craftsmanship', label: '기술력', value: 94 },
      { key: 'resale', label: '환금성', value: 82 },
      { key: 'prestige', label: '브랜드 가치', value: 92 },
    ],
  },
  // B티어 — 양반 (프리미엄 럭셔리)
  {
    id: 310,
    name: '오메가',
    slug: 'omega',
    logo_url: WATCH_BRAND_LOGOS['오메가'],
    tier: 'B' as TierLevel,
    tier_score: 88.0,
    description: '스피드마스터로 달에 간 시계, 호불호 없는 정답',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 95 },
      { key: 'craftsmanship', label: '기술력', value: 90 },
      { key: 'resale', label: '환금성', value: 80 },
      { key: 'prestige', label: '브랜드 가치', value: 88 },
    ],
  },
  {
    id: 311,
    name: '까르띠에',
    slug: 'cartier',
    logo_url: WATCH_BRAND_LOGOS['까르띠에'],
    tier: 'B' as TierLevel,
    tier_score: 87.5,
    description: '왕의 보석상, 산토스와 탱크의 클래식',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 96 },
      { key: 'craftsmanship', label: '기술력', value: 85 },
      { key: 'resale', label: '환금성', value: 82 },
      { key: 'prestige', label: '브랜드 가치', value: 90 },
    ],
  },
  {
    id: 312,
    name: 'IWC',
    slug: 'iwc',
    logo_url: WATCH_BRAND_LOGOS['IWC'],
    tier: 'B' as TierLevel,
    tier_score: 86.0,
    description: '파일럿 워치의 대명사, 엔지니어링의 정수',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 90 },
      { key: 'craftsmanship', label: '기술력', value: 88 },
      { key: 'resale', label: '환금성', value: 78 },
      { key: 'prestige', label: '브랜드 가치', value: 86 },
    ],
  },
  {
    id: 313,
    name: '파네라이',
    slug: 'panerai',
    logo_url: WATCH_BRAND_LOGOS['파네라이'],
    tier: 'B' as TierLevel,
    tier_score: 85.0,
    description: '이탈리아 해군의 시계, 강렬한 존재감',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 88 },
      { key: 'craftsmanship', label: '기술력', value: 85 },
      { key: 'resale', label: '환금성', value: 75 },
      { key: 'prestige', label: '브랜드 가치', value: 84 },
    ],
  },
  {
    id: 314,
    name: '그랜드 세이코',
    slug: 'grand-seiko',
    logo_url: WATCH_BRAND_LOGOS['그랜드 세이코'],
    tier: 'B' as TierLevel,
    tier_score: 84.0,
    description: '일본 장인 정신의 결정체, 스프링 드라이브의 혁신',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 85 },
      { key: 'craftsmanship', label: '기술력', value: 92 },
      { key: 'resale', label: '환금성', value: 70 },
      { key: 'prestige', label: '브랜드 가치', value: 82 },
    ],
  },
  // C티어 — 중인 (매스티지)
  {
    id: 315,
    name: '태그호이어',
    slug: 'tag-heuer',
    logo_url: WATCH_BRAND_LOGOS['태그호이어'],
    tier: 'C' as TierLevel,
    tier_score: 78.0,
    description: '사회초년생의 로망, 모터스포츠와 함께한 역사',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 82 },
      { key: 'craftsmanship', label: '기술력', value: 78 },
      { key: 'resale', label: '환금성', value: 65 },
      { key: 'prestige', label: '브랜드 가치', value: 80 },
    ],
  },
  {
    id: 316,
    name: '튜더',
    slug: 'tudor',
    logo_url: WATCH_BRAND_LOGOS['튜더'],
    tier: 'C' as TierLevel,
    tier_score: 77.0,
    description: '롤렉스의 동생, 가성비 최고의 럭셔리',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 78 },
      { key: 'craftsmanship', label: '기술력', value: 80 },
      { key: 'resale', label: '환금성', value: 72 },
      { key: 'prestige', label: '브랜드 가치', value: 78 },
    ],
  },
  {
    id: 317,
    name: '론진',
    slug: 'longines',
    logo_url: WATCH_BRAND_LOGOS['론진'],
    tier: 'C' as TierLevel,
    tier_score: 75.0,
    description: '190년 역사의 근본, 우아한 클래식 디자인',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 88 },
      { key: 'craftsmanship', label: '기술력', value: 75 },
      { key: 'resale', label: '환금성', value: 60 },
      { key: 'prestige', label: '브랜드 가치', value: 75 },
    ],
  },
  {
    id: 318,
    name: '브라이틀링',
    slug: 'breitling',
    logo_url: WATCH_BRAND_LOGOS['브라이틀링'],
    tier: 'C' as TierLevel,
    tier_score: 76.0,
    description: '항공 크로노그래프의 선구자, 나비타이머의 전설',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 85 },
      { key: 'craftsmanship', label: '기술력', value: 80 },
      { key: 'resale', label: '환금성', value: 62 },
      { key: 'prestige', label: '브랜드 가치', value: 76 },
    ],
  },
  {
    id: 319,
    name: '노모스',
    slug: 'nomos',
    logo_url: WATCH_BRAND_LOGOS['노모스'],
    tier: 'C' as TierLevel,
    tier_score: 74.0,
    description: '독일 바우하우스 디자인, 미니멀한 아름다움',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 70 },
      { key: 'craftsmanship', label: '기술력', value: 82 },
      { key: 'resale', label: '환금성', value: 58 },
      { key: 'prestige', label: '브랜드 가치', value: 72 },
    ],
  },
  // D티어 — 평민 (엔트리 & 툴워치)
  {
    id: 320,
    name: '티쏘',
    slug: 'tissot',
    logo_url: WATCH_BRAND_LOGOS['티쏘'],
    tier: 'D' as TierLevel,
    tier_score: 65.0,
    description: 'PRX로 부활, 국밥처럼 든든한 입문용 시계',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 72 },
      { key: 'craftsmanship', label: '기술력', value: 68 },
      { key: 'resale', label: '환금성', value: 45 },
      { key: 'prestige', label: '브랜드 가치', value: 65 },
    ],
  },
  {
    id: 321,
    name: '해밀턴',
    slug: 'hamilton',
    logo_url: WATCH_BRAND_LOGOS['해밀턴'],
    tier: 'D' as TierLevel,
    tier_score: 64.0,
    description: '카키필드의 전설, 영화 속 단골 시계',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 75 },
      { key: 'craftsmanship', label: '기술력', value: 65 },
      { key: 'resale', label: '환금성', value: 42 },
      { key: 'prestige', label: '브랜드 가치', value: 62 },
    ],
  },
  {
    id: 322,
    name: '세이코',
    slug: 'seiko',
    logo_url: WATCH_BRAND_LOGOS['세이코'],
    tier: 'D' as TierLevel,
    tier_score: 62.0,
    description: '쿼츠 혁명의 주역, 가성비 기계식의 대명사',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 80 },
      { key: 'craftsmanship', label: '기술력', value: 70 },
      { key: 'resale', label: '환금성', value: 40 },
      { key: 'prestige', label: '브랜드 가치', value: 58 },
    ],
  },
  {
    id: 323,
    name: '카시오 / 지샥',
    slug: 'casio-gshock',
    logo_url: WATCH_BRAND_LOGOS['카시오'],
    tier: 'D' as TierLevel,
    tier_score: 60.0,
    description: '진정한 실용성과 내구성의 끝판왕, 툴워치의 정석',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 65 },
      { key: 'craftsmanship', label: '기술력', value: 72 },
      { key: 'resale', label: '환금성', value: 30 },
      { key: 'prestige', label: '브랜드 가치', value: 50 },
    ],
  },
  {
    id: 324,
    name: '애플워치 / 갤럭시워치',
    slug: 'smartwatch',
    logo_url: WATCH_BRAND_LOGOS['애플'],
    tier: 'D' as TierLevel,
    tier_score: 55.0,
    description: '일상을 지배한 스마트워치, 기능성의 끝',
    category: 'mens-watch',
    scores: [
      { key: 'heritage', label: '역사/전통', value: 20 },
      { key: 'craftsmanship', label: '기술력', value: 85 },
      { key: 'resale', label: '환금성', value: 25 },
      { key: 'prestige', label: '브랜드 가치', value: 45 },
    ],
  },
];

export const WATCH_CATEGORY: Category = {
  id: 3,
  slug: 'mens-watch',
  name: '남자시계',
  description: '남자 시계 브랜드 계급도 - 커뮤니티 반응 기반',
  icon: '⌚',
  display_order: 3,
  is_active: true,
  spec_definitions: [
    { key: 'price_range', label: '가격대', type: 'text' },
    { key: 'movement', label: '무브먼트', type: 'select', options: [
      { value: 'mechanical', label: '기계식' },
      { value: 'automatic', label: '오토매틱' },
      { value: 'quartz', label: '쿼츠' },
      { value: 'smart', label: '스마트' },
    ]},
    { key: 'case_size', label: '케이스 크기', unit: 'mm', type: 'number' },
    { key: 'water_resistance', label: '방수', unit: 'ATM', type: 'number' },
  ],
  score_definitions: [
    { key: 'heritage', label: '역사/전통', weight: 25 },
    { key: 'craftsmanship', label: '기술력', weight: 30 },
    { key: 'resale', label: '환금성', weight: 20 },
    { key: 'prestige', label: '브랜드 가치', weight: 25 },
  ],
  brand_score_definitions: [
    { key: 'heritage', label: '역사/전통', weight: 25 },
    { key: 'craftsmanship', label: '기술력', weight: 30 },
    { key: 'resale', label: '환금성', weight: 20 },
    { key: 'prestige', label: '브랜드 가치', weight: 25 },
  ],
  filter_definitions: {
    product_type: [
      { value: 'dress', label: '드레스워치' },
      { value: 'sport', label: '스포츠워치' },
      { value: 'diver', label: '다이버워치' },
      { value: 'pilot', label: '파일럿워치' },
      { value: 'chronograph', label: '크로노그래프' },
    ],
    usage: [
      { value: 'formal', label: '격식/비즈니스' },
      { value: 'casual', label: '캐주얼' },
      { value: 'sport', label: '스포츠/활동' },
      { value: 'collection', label: '컬렉션/투자' },
    ],
  },
  quiz_definitions: [
    {
      key: 'budget',
      question: '예산은 어느 정도인가요?',
      emoji: '💰',
      options: [
        { value: 'entry', label: '100만원 이하', description: '입문용 가성비 시계' },
        { value: 'mid', label: '100~500만원', description: '첫 명품 시계' },
        { value: 'premium', label: '500~1500만원', description: '프리미엄 럭셔리' },
        { value: 'luxury', label: '1500만원 이상', description: '하이엔드 컬렉션' },
      ],
    },
    {
      key: 'style',
      question: '선호하는 스타일은?',
      emoji: '🎨',
      options: [
        { value: 'classic', label: '클래식/드레스', description: '우아하고 격식있는' },
        { value: 'sport', label: '스포티/다이버', description: '활동적이고 견고한' },
        { value: 'minimal', label: '미니멀/모던', description: '깔끔하고 심플한' },
        { value: 'bold', label: '존재감/볼드', description: '강렬한 디자인' },
      ],
    },
    {
      key: 'occasion',
      question: '주로 어떤 상황에서 착용하나요?',
      emoji: '👔',
      options: [
        { value: 'office', label: '출근/비즈니스', description: '정장에 어울리는' },
        { value: 'daily', label: '일상/캐주얼', description: '매일 편하게' },
        { value: 'special', label: '특별한 날', description: '기념일/행사용' },
        { value: 'outdoor', label: '아웃도어/스포츠', description: '활동적인 상황' },
      ],
    },
    {
      key: 'priority',
      question: '가장 중요하게 생각하는 것은?',
      emoji: '⭐',
      options: [
        { value: 'brand', label: '브랜드 가치', description: '남들이 알아보는' },
        { value: 'movement', label: '무브먼트/기술력', description: '시계의 심장' },
        { value: 'design', label: '디자인', description: '보는 즐거움' },
        { value: 'investment', label: '투자/리셀 가치', description: '가치 상승 기대' },
      ],
    },
  ],
};

// 시계 퀴즈 추천 결과
export const WATCH_RECOMMENDATIONS = {
  'entry_classic_office': [
    { slug: 'tissot', name: '티쏘 PRX', brand: '티쏘', match: 95, reason: '클래식한 디자인에 합리적인 가격, 출근용 완벽' },
    { slug: 'longines', name: '론진 마스터 컬렉션', brand: '론진', match: 88, reason: '190년 역사의 격식있는 드레스워치' },
    { slug: 'hamilton', name: '해밀턴 재즈마스터', brand: '해밀턴', match: 82, reason: '가성비 좋은 우아한 드레스워치' },
  ],
  'mid_sport_daily': [
    { slug: 'tudor', name: '튜더 블랙베이', brand: '튜더', match: 96, reason: '롤렉스의 동생, 매일 착용하기 좋은 스포츠워치' },
    { slug: 'tag-heuer', name: '태그호이어 아쿠아레이서', brand: '태그호이어', match: 90, reason: '모터스포츠 감성의 데일리 워치' },
    { slug: 'breitling', name: '브라이틀링 슈퍼오션', brand: '브라이틀링', match: 85, reason: '항공 DNA의 견고한 다이버' },
  ],
  'premium_classic_special': [
    { slug: 'omega', name: '오메가 스피드마스터', brand: '오메가', match: 97, reason: '달에 간 시계, 특별한 날의 동반자' },
    { slug: 'cartier', name: '까르띠에 산토스', brand: '까르띠에', match: 92, reason: '세계 최초의 파일럿 워치, 클래식의 정수' },
    { slug: 'iwc', name: 'IWC 포르투기저', brand: 'IWC', match: 88, reason: '우아한 대형 드레스워치의 명작' },
  ],
  'luxury_bold_special': [
    { slug: 'rolex', name: '롤렉스 서브마리너', brand: '롤렉스', match: 98, reason: '시계의 왕, 최고의 환금성과 인지도' },
    { slug: 'audemars-piguet', name: '오데마 피게 로열 오크', brand: '오데마 피게', match: 95, reason: '럭셔리 스포츠워치의 전설' },
    { slug: 'patek-philippe', name: '파텍 필립 노틸러스', brand: '파텍 필립', match: 92, reason: '시계 컬렉터의 최종 목표' },
  ],
  'default': [
    { slug: 'rolex', name: '롤렉스', brand: '롤렉스', match: 95, reason: '시계질의 끝은 결돌롤, 대체 불가능한 브랜드' },
    { slug: 'omega', name: '오메가 스피드마스터', brand: '오메가', match: 90, reason: '호불호 없는 정답, 달에 간 시계' },
    { slug: 'tudor', name: '튜더 블랙베이', brand: '튜더', match: 85, reason: '가성비 최고의 럭셔리 스포츠워치' },
  ],
};

// Mock 데이터 함수
export function getMockBrands(category: string): Brand[] | null {
  if (category === 'chicken') {
    return CHICKEN_BRANDS;
  }
  if (category === 'running-shoes') {
    return RUNNING_SHOES_BRANDS;
  }
  if (category === 'mens-watch') {
    return WATCH_BRANDS;
  }
  return null;
}

// 제품(메뉴) 데이터 반환 함수
export function getMockProducts(category: string): Brand[] | null {
  if (category === 'chicken') {
    return CHICKEN_MENUS;
  }
  // 다른 카테고리의 제품 데이터는 필요시 추가
  return null;
}

export function getMockCategory(slug: string): Category | null {
  if (slug === 'chicken') {
    return CHICKEN_CATEGORY;
  }
  if (slug === 'running-shoes') {
    return RUNNING_SHOES_CATEGORY;
  }
  if (slug === 'mens-watch') {
    return WATCH_CATEGORY;
  }
  return null;
}
